# Auto-generated format file for document type: apex_template
# Generated by FormatGeneratorAgent on 2026-06-04T10:31:46.419768

# Auto-generated format file for document type: apex_template
# Generated by FormatGeneratorAgent

from __future__ import annotations
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, field_validator


class AdjustmentDetail(BaseModel):
    """Represents a single adjustment code paired with its amount."""
    
    value: Optional[float] = Field(
        None,
        description="The adjustment amount for this code (e.g., 280.00, 21.00)."
    )
    code: Optional[str] = Field(
        None,
        description="The adjustment code (e.g., 'CO-24', 'PR-96')."
    )


class ServiceLine(BaseModel):
    """Represents an individual service line within a WPS GHA MAC J5 ERA remittance claim."""

    rendering_provider: Optional[str] = Field(None, description="Rendering provider name (e.g., 'NW IA VISIO').")
    service_date: Optional[str] = Field(None, description="Service date range (e.g., '07/31-07/31/25').")
    pos: Optional[str] = Field(None, description="Place of service code (e.g., '11').")
    nos: Optional[str] = Field(None, description="Number of services (e.g., '1').")
    proc_code: Optional[str] = Field(None, description="Procedure code (e.g., '92014', '92015').")
    mods: Optional[str] = Field(None, description="Procedure modifiers if any.")
    billed_amount: Optional[float] = Field(None, description="Billed amount (e.g., 280.00, 21.00).")
    allowed_amount: Optional[float] = Field(None, description="Allowed amount (e.g., 0.00, 119.78).")
    deduct_amount: Optional[float] = Field(None, description="Deductible amount (e.g., 0.00, 119.78).")
    coins_amount: Optional[float] = Field(None, description="Coinsurance amount (e.g., 0.00).")
    adjustment_codes_with_values: Optional[List[AdjustmentDetail]] = Field(
        default_factory=list,
        description="Array of adjustment codes paired with their respective amounts (e.g., [{'value': 280.00, 'code': 'CO-24'}, {'value': 21.00, 'code': 'PR-96'}]). Use this field when you need to correlate individual amounts with their codes."
    )
    prov_pd: Optional[float] = Field(None, description="Provider paid amount (e.g., 0.00).")
    remark_codes: Optional[str] = Field(None, description="Remark codes (e.g., 'N130', 'MA01').")

    @field_validator("proc_code", "mods", "remark_codes", mode="before")
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v


class ClaimModel(BaseModel):
    """Represents a full claim within a WPS GHA MAC J5 ERA remittance document."""

    patient_name: Optional[str] = Field(None, description="Patient name (e.g., 'DACKEN, ALLAN').")
    hic: Optional[str] = Field(None, description="HIC number (e.g., '9KK1T47WU32').")
    acnt: Optional[str] = Field(None, description="Account number (e.g., 'SE33652').")
    icn: Optional[str] = Field(None, description="ICN number (e.g., '0926148098080').")
    asg: Optional[str] = Field(None, description="Assignment indicator (e.g., 'Y').")
    moa: Optional[str] = Field(None, description="MOA codes (e.g., 'MA01', 'MA01 MA18').")
    pt_resp: Optional[float] = Field(None, description="Patient responsibility amount (e.g., 21.00, 119.78).")
    claim_total_billed: Optional[float] = Field(None, description="Claim total billed (e.g., 301.00, 280.00).")
    claim_total_allowed: Optional[float] = Field(None, description="Claim total allowed (e.g., 0.00, 119.78).")
    claim_total_deduct: Optional[float] = Field(None, description="Claim total deductible (e.g., 0.00, 119.78).")
    claim_total_coins: Optional[float] = Field(None, description="Claim total coinsurance (e.g., 0.00).")
    claim_total_grp_rc_amt: Optional[float] = Field(None, description="Claim total group/RC amount (e.g., 301.00).")
    claim_total_prov_pd: Optional[float] = Field(None, description="Claim total provider paid (e.g., 0.00).")
    prev_pd: Optional[float] = Field(None, description="Previous paid amount (e.g., 0.00).")
    interest: Optional[float] = Field(None, description="Interest amount (e.g., 0.00).")
    late_filing_charge: Optional[float] = Field(None, description="Late filing charge (e.g., 0.00).")
    net: Optional[float] = Field(None, description="Net amount (e.g., 0.00).")
    forwarded_to: Optional[str] = Field(None, description="Claim forwarded to (e.g., 'WELLMARK BCBS OF IA MEDIGAP').")
    services: List[ServiceLine] = Field(default_factory=list, description="All service line items within this claim.")

    @field_validator("moa", "forwarded_to", mode="before")
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v


class ResponseModel(BaseModel):
    """Top-level response model for apex_template (WPS GHA MAC J5 ERA Remittance)."""

    client_id: Optional[str] = Field(None, description="Client ID (e.g., 'C69').")
    report_name: Optional[str] = Field(None, description="Report name (e.g., 'ERA_WPS_GHA__MAC_J5_PART_318370175_060326_0000.C69').")
    payer_report: Optional[str] = Field(None, description="Payer report number (e.g., 'E060326011.WMO').")
    payer_name: Optional[str] = Field(None, description="Payer name (e.g., 'WPS GHA - MAC J5 PART B').")
    date: Optional[str] = Field(None, description="Check/EFT date (e.g., '06/02/2026').")
    payment_method: Optional[str] = Field(None, description="Payment method (e.g., 'Non-Payment Data').")
    check_eft_number: Optional[str] = Field(None, description="Check/EFT number (e.g., '318370175').")
    summary_total_claims: Optional[int] = Field(None, description="Total claims count (e.g., 3).")
    summary_billed_amount: Optional[float] = Field(None, description="Summary billed amount (e.g., 871.00).")
    summary_total_reason_code_adjustment: Optional[float] = Field(None, description="Total reason code adjustment (e.g., 637.37).")
    summary_total_allowed_amount: Optional[float] = Field(None, description="Summary total allowed amount (e.g., 233.63).")
    summary_total_coinsurance_amount: Optional[float] = Field(None, description="Summary total coinsurance (e.g., 0.00).")
    summary_total_deductible_amount: Optional[float] = Field(None, description="Summary total deductible (e.g., 233.63).")
    summary_total_paid_to_provider: Optional[float] = Field(None, description="Summary total paid to provider (e.g., 0.00).")
    summary_total_interest_amount: Optional[float] = Field(None, description="Summary total interest (e.g., 0.00).")
    summary_total_check_eft_amount: Optional[float] = Field(None, description="Summary total check/EFT amount (e.g., 0.00).")
    claims: List[ClaimModel] = Field(default_factory=list, description="All claims extracted from the document.")


class BatchModel(BaseModel):
    """Model for validating a single batch of claims."""
    claims: List[ClaimModel] = Field(..., description="List of claims found in this batch")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Batch-level metadata")


def map_extracted_data(extracted_claims: List[dict], aggregated_metadata: dict) -> dict:
    """Maps raw AI extraction output into the final apex_template hierarchy."""
    nested = aggregated_metadata.get("apex_template_remittance_page", {})
    if not isinstance(nested, dict):
        nested = {}

    merged = {**nested, **aggregated_metadata}

    return {
        "client_id": merged.get("client_id"),
        "report_name": merged.get("report_name"),
        "payer_report": merged.get("payer_report"),
        "payer_name": merged.get("payer_name"),
        "date": merged.get("date"),
        "payment_method": merged.get("payment_method"),
        "check_eft_number": merged.get("check_eft_number"),
        "summary_total_claims": merged.get("summary_total_claims"),
        "summary_billed_amount": merged.get("summary_billed_amount"),
        "summary_total_reason_code_adjustment": merged.get("summary_total_reason_code_adjustment"),
        "summary_total_allowed_amount": merged.get("summary_total_allowed_amount"),
        "summary_total_coinsurance_amount": merged.get("summary_total_coinsurance_amount"),
        "summary_total_deductible_amount": merged.get("summary_total_deductible_amount"),
        "summary_total_paid_to_provider": merged.get("summary_total_paid_to_provider"),
        "summary_total_interest_amount": merged.get("summary_total_interest_amount"),
        "summary_total_check_eft_amount": merged.get("summary_total_check_eft_amount"),
        "claims": extracted_claims,
    }


SCHEMA_DESCRIPTION = """
### DOCUMENT TYPE: WPS GHA MAC J5 Part B ERA Remittance (apex_template)
This is an Ensora Clearinghouse ERA remittance notice from WPS GHA - MAC J5 PART B (Medicare).

### DOCUMENT STRUCTURE:

1. **HEADER BLOCK** (top of document):
   - Client ID, Report Name, Payer Report → `client_id`, `report_name`, `payer_report`
   - Payer, Date, Payment Method, Check/EFT # → `payer_name`, `date`, `payment_method`, `check_eft_number`

2. **CLAIM BLOCK** (one per patient, repeating):
   - NAME, HIC, ACNT, ICN, ASG, MOA → ClaimModel header fields
   - SERVICE LINE TABLE: REND PROV, SERV DATE, POS, NOS, PROC, MODS, BILLED, ALLOWED, DEDUCT, COINS, GRP/RC-AMT, PROV PD → ServiceLine fields
   - REMARK codes per service line → `remark_codes`
   - PT RESP and CLAIM TOTALS row → `pt_resp`, claim_total_* fields
   - ADJ. TO TOTALS: PREV PD, INTEREST, LATE FILING CHARGE, NET → ClaimModel adj fields
   - Optional Note: CLAIM INFORMATION FORWARDED TO → `forwarded_to`

3. **SUMMARY BLOCK** (bottom of page):
   - Payer, Check/EFT Date, Check/EFT #, Total Claims → metadata summary fields
   - Billed Amount, Total Reason Code Adjustment, Total Allowed, Total Coinsurance, Total Deductible, Total Paid to Provider, Total Interest, Total Check/EFT Amount → summary_* metadata fields

### KEY EXTRACTION RULES:
- Each NAME: block = one ClaimModel with nested ServiceLine list.
- GRP/RC-AMT column contains group/reason codes paired with adjustment amounts (e.g., 'CO-24 280.00', 'PR-96 21.00').
- Extract GRP/RC-AMT values into `adjustment_codes_with_values` as a list of adjustment codes paired with their respective amounts: `[{"value": 280.00, "code": "CO-24"}, {"value": 21.00, "code": "PR-96"}]`.
- Parse group prefix (e.g. CO, PR, OA, PI) + hyphen + code (e.g. CO-24) into the `code` field, and the float amount that follows into the `value` field.
- Parse all dollar amounts as floats; strip $ signs.
- MOA codes are space-separated (e.g., 'MA01 MA18').
- metadata captures all header and summary fields.
"""


def section_builder(text: str) -> List[Dict[str, str]]:
    """Identify apex_template claim block boundaries using regex on raw text."""
    import re
    sections = []

    claim_pattern = r"NAME:\s+([A-Z,\s]+)"
    matches = list(re.finditer(claim_pattern, text, re.IGNORECASE))

    if not matches:
        return [{"type": "content", "text": text}]

    for i, match in enumerate(matches):
        start_pos = match.start()
        end_pos = matches[i + 1].start() if i + 1 < len(matches) else len(text)

        sections.append({
            "type": "claim_block",
            "patient_name_hint": match.group(1).strip(),
            "text": text[start_pos:end_pos],
        })

    return sections


def calculate_totals(claims_data: dict) -> dict:
    """Calculate format-specific totals for the final apex_template response."""
    total_billed = 0.0
    total_allowed = 0.0
    total_deduct = 0.0
    total_coins = 0.0
    total_prov_pd = 0.0

    claims = claims_data.get("claims") or []

    for claim in claims:
        total_billed += float(claim.get("claim_total_billed") or 0)
        total_allowed += float(claim.get("claim_total_allowed") or 0)
        total_deduct += float(claim.get("claim_total_deduct") or 0)
        total_coins += float(claim.get("claim_total_coins") or 0)
        total_prov_pd += float(claim.get("claim_total_prov_pd") or 0)

    return {
        "summary_billed_amount": round(total_billed, 2),
        "summary_total_allowed_amount": round(total_allowed, 2),
        "summary_total_deductible_amount": round(total_deduct, 2),
        "summary_total_coinsurance_amount": round(total_coins, 2),
        "summary_total_paid_to_provider": round(total_prov_pd, 2),
        "summary_total_claims": len(claims),
    }