# Auto-generated format file for document type: availity_bcbs_live
# Generated by FormatGeneratorAgent on 2026-03-30T10:50:04.816223

# Auto-generated format file for document type: availity_bcbs_live
# Generated by FormatGeneratorAgent

from __future__ import annotations
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, field_validator


class AdjustmentDetail(BaseModel):
    """Represents a single adjustment code paired with its amount."""
    
    code: Optional[str] = Field(
        None,
        description="Adjustment group/reason code (e.g., 'CO-45', 'OA-23')."
    )
    value: Optional[float] = Field(
        None,
        description="The adjustment amount for this code (e.g., 45.11, 94.35)."
    )


class ServiceLine(BaseModel):
    """Represents an individual service line within a BCBS remittance advice claim."""

    line_ctrl_number: Optional[str] = Field(
        None,
        description="Line control number (e.g., '1', '2')."
    )
    date_from: Optional[str] = Field(
        None,
        description="Service date from (e.g., '09/29/2025')."
    )
    date_to: Optional[str] = Field(
        None,
        description="Service date to (e.g., '09/29/2025')."
    )
    rend_prov_id: Optional[str] = Field(
        None,
        description="Rendering provider ID."
    )
    rev: Optional[str] = Field(
        None,
        description="Revenue code."
    )
    sub_proc_modifier_units: Optional[str] = Field(
        None,
        description="Submitted procedure/modifier/units (e.g., '92014 / / 1')."
    )
    adjud_proc_modifier_units: Optional[str] = Field(
        None,
        description="Adjudicated procedure/modifier/units (e.g., 'HC:92014 / / 1')."
    )
    remark_payer_code: Optional[str] = Field(
        None,
        description="Remark/payer code (e.g., 'N219')."
    )
    supp_info_amt_code: Optional[str] = Field(
        None,
        description="Supplemental info AMT code (e.g., 'B6')."
    )
    supp_info_amt_value: Optional[float] = Field(
        None,
        description="Supplemental info AMT value (e.g., 22.54)."
    )
    charge: Optional[float] = Field(
        None,
        description="Billed charge amount (e.g., 160.00)."
    )
    adj_qty: Optional[str] = Field(
        None,
        description="[DEPRECATED] Single adjustment group/reason code (e.g., 'OA-23'). Use adjustment_codes_with_values for multiple adjustments."
    )
    adj_amount: Optional[float] = Field(
        None,
        description="[DEPRECATED] Single adjustment amount (e.g., 137.46). Use adjustment_codes_with_values for multiple adjustments."
    )
    adjustment_codes_with_values: Optional[List[AdjustmentDetail]] = Field(
        default_factory=list,
        description="Array of adjustment codes paired with their respective amounts (e.g., [{'code': 'OA-23', 'value': 137.46}, {'code': 'CO-45', 'value': 45.11}]). Use this field to capture multiple adjustments per service line."
    )
    payment: Optional[float] = Field(
        None,
        description="Payment amount for this line (e.g., 22.54)."
    )

    @field_validator("sub_proc_modifier_units", "adjud_proc_modifier_units", "remark_payer_code", mode="before")
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v


class ClaimModel(BaseModel):
    """Represents a full claim within a BCBS/Regence remittance advice document."""

    payer_name: Optional[str] = Field(
        None,
        description="Payer name (e.g., 'REGENCE BLUECROSS BLUESHIELD OF UTAH')."
    )
    payer_address: Optional[str] = Field(
        None,
        description="Payer address (e.g., 'PO BOX 30270 SALT LAKE CITY, UT 84130')."
    )
    payee_tax_id: Optional[str] = Field(
        None,
        description="Payee tax ID (e.g., '830747842')."
    )
    payee_id: Optional[str] = Field(
        None,
        description="Payee ID (e.g., '1972095172')."
    )
    check_eft_trace_number: Optional[str] = Field(
        None,
        description="Check/EFT trace number (e.g., '0081972639')."
    )
    payment_amount: Optional[float] = Field(
        None,
        description="Payment amount (e.g., 29.14)."
    )
    check_eft_date: Optional[str] = Field(
        None,
        description="Check/EFT date (e.g., '11/26/2025')."
    )
    production_end_cycle_date: Optional[str] = Field(
        None,
        description="Production end cycle date (e.g., '11/24/2025')."
    )
    payee_name: Optional[str] = Field(
        None,
        description="Payee name (e.g., 'ROGERS EYE CENTER PC')."
    )
    payee_address: Optional[str] = Field(
        None,
        description="Payee address (e.g., '285 MAIN ST SAVANNAH, TN 383722050')."
    )
    transaction_date: Optional[str] = Field(
        None,
        description="Transaction date (e.g., 'November 26, 2025')."
    )
    patient_name: Optional[str] = Field(
        None,
        description="Patient name (e.g., 'DUFEL, CHERIE L')."
    )
    claim_number: Optional[str] = Field(
        None,
        description="Claim number (e.g., 'E71808036700')."
    )
    claim_date_from: Optional[str] = Field(
        None,
        description="Claim date from (e.g., '09/29/2025')."
    )
    claim_date_to: Optional[str] = Field(
        None,
        description="Claim date to (e.g., '09/29/2025')."
    )
    claim_status_code: Optional[str] = Field(
        None,
        description="Claim status code (e.g., '2')."
    )
    patient_id: Optional[str] = Field(
        None,
        description="Patient ID (e.g., '140203934')."
    )
    patient_ctrl_number: Optional[str] = Field(
        None,
        description="Patient control number (e.g., '67659')."
    )
    rendering_provider: Optional[str] = Field(
        None,
        description="Rendering provider name (e.g., 'JONES, PATRICK')."
    )
    rendering_prv_id: Optional[str] = Field(
        None,
        description="Rendering provider ID (e.g., '1487182754')."
    )
    original_ref_number: Optional[str] = Field(
        None,
        description="Original reference number."
    )
    group_policy: Optional[str] = Field(
        None,
        description="Group/policy (e.g., 'NONPAR')."
    )
    contract_hdr: Optional[str] = Field(
        None,
        description="Contract header (e.g., 'NONPAR')."
    )
    facility_type: Optional[str] = Field(
        None,
        description="Facility type code (e.g., '11')."
    )
    claim_frequency: Optional[str] = Field(
        None,
        description="Claim frequency code (e.g., '1')."
    )
    claim_charge: Optional[float] = Field(
        None,
        description="Total claim charge (e.g., 225.00)."
    )
    claim_payment: Optional[float] = Field(
        None,
        description="Claim payment amount (e.g., 29.14)."
    )
    patient_resp: Optional[float] = Field(
        None,
        description="Patient responsibility (e.g., 0.00)."
    )
    claim_received_date: Optional[str] = Field(
        None,
        description="Claim received date (e.g., '11/04/2025')."
    )
    supplemental_info: Optional[str] = Field(
        None,
        description="Supplemental AMT/payer codes (e.g., '$29.14 (AU)')."
    )
    services: List[ServiceLine] = Field(
        default_factory=list,
        description="All service line items within this claim."
    )
    remark_codes: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="Remark code descriptions (e.g., [{'code': 'N219', 'description': '...'}])."
    )
    amt_codes: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="AMT code descriptions (e.g., [{'code': 'B6', 'description': '...'}])."
    )
    group_codes: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="Group code descriptions (e.g., [{'code': 'OA', 'description': '...'}])."
    )
    claim_adjustment_reason_codes: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="Claim adjustment reason codes/descriptions."
    )
    claim_status_codes: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="Claim status code descriptions."
    )

    @field_validator("claim_status_code", "facility_type", "claim_frequency", mode="before")
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v


class ResponseModel(BaseModel):
    """Top-level response model for availity_bcbs_live (BCBS/Regence Remittance Advice)."""

    payer_name: Optional[str] = Field(
        None,
        description="Payer name (e.g., 'REGENCE BLUECROSS BLUESHIELD OF UTAH')."
    )
    payer_address: Optional[str] = Field(
        None,
        description="Payer address (e.g., 'PO BOX 30270 SALT LAKE CITY, UT 84130')."
    )
    payee_name: Optional[str] = Field(
        None,
        description="Payee name (e.g., 'ROGERS EYE CENTER PC')."
    )
    payee_address: Optional[str] = Field(
        None,
        description="Payee address (e.g., '285 MAIN ST SAVANNAH, TN 383722050')."
    )
    payee_tax_id: Optional[str] = Field(
        None,
        description="Payee tax ID (e.g., '830747842')."
    )
    payee_id: Optional[str] = Field(
        None,
        description="Payee ID (e.g., '1972095172')."
    )
    check_eft_trace_number: Optional[str] = Field(
        None,
        description="Check/EFT trace number (e.g., '0081972639')."
    )
    payment_amount: Optional[float] = Field(
        None,
        description="Total payment amount (e.g., 29.14)."
    )
    check_eft_date: Optional[str] = Field(
        None,
        description="Check/EFT date (e.g., '11/26/2025')."
    )
    production_end_cycle_date: Optional[str] = Field(
        None,
        description="Production end cycle date (e.g., '11/24/2025')."
    )
    transaction_date: Optional[str] = Field(
        None,
        description="Transaction date (e.g., 'November 26, 2025')."
    )
    claims: List[ClaimModel] = Field(
        default_factory=list,
        description="All claims extracted from the document."
    )


class BatchModel(BaseModel):
    """Model for validating a single batch of claims."""
    claims: List[ClaimModel] = Field(..., description="List of claims found in this batch")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Batch-level metadata")


def map_extracted_data(extracted_claims: List[dict], aggregated_metadata: dict) -> dict:
    """Maps raw AI extraction output into the final availity_bcbs_live hierarchy."""
    nested = aggregated_metadata.get("availity_bcbs_live_remittance_page", {})
    if not isinstance(nested, dict):
        nested = {}

    merged = {**nested, **aggregated_metadata}

    return {
        "payer_name": merged.get("payer_name"),
        "payer_address": merged.get("payer_address"),
        "payee_name": merged.get("payee_name"),
        "payee_address": merged.get("payee_address"),
        "payee_tax_id": merged.get("payee_tax_id"),
        "payee_id": merged.get("payee_id"),
        "check_eft_trace_number": merged.get("check_eft_trace_number"),
        "payment_amount": merged.get("payment_amount"),
        "check_eft_date": merged.get("check_eft_date"),
        "production_end_cycle_date": merged.get("production_end_cycle_date"),
        "transaction_date": merged.get("transaction_date"),
        "claims": extracted_claims,
    }


SCHEMA_DESCRIPTION = """
### DOCUMENT TYPE: BCBS/Regence Remittance Advice (availity_bcbs_live)
This is a Regence BlueCross BlueShield remittance/EOB document via Availity.

### DOCUMENT STRUCTURE:

1. **CHECK SUMMARY BLOCK** (top of page):
   - Payer: 'REGENCE BLUECROSS BLUESHIELD OF UTAH', 'PO BOX 30270 SALT LAKE CITY, UT 84130' → `payer_name`, `payer_address`
   - Payee Tax ID, Payee ID → `payee_tax_id`, `payee_id`
   - Check/EFT Trace Number, Payment Amount, Check/EFT Date → `check_eft_trace_number`, `payment_amount`, `check_eft_date`
   - Production End Cycle Date → `production_end_cycle_date`
   - Payee Name, Payee Address → `payee_name`, `payee_address`
   - Transaction Date (top-right, e.g., 'November 26, 2025') → `transaction_date`

2. **CLAIM SUMMARY BLOCK** (per claim):
   - Patient Name, Claim Number, Claim Date (from-to) → `patient_name`, `claim_number`, `claim_date_from`, `claim_date_to`
   - Claim Status Code → `claim_status_code`
   - Patient ID, Patient Ctrl Nmbr → `patient_id`, `patient_ctrl_number`
   - Rendering Prvd, Rendering Prv ID → `rendering_provider`, `rendering_prv_id`
   - Original Ref Nmbr → `original_ref_number`
   - Group/Policy, Contract Hdr → `group_policy`, `contract_hdr`
   - Facility Type, Claim Frequency → `facility_type`, `claim_frequency`
   - Claim Charge, Claim Payment, Patient Resp → `claim_charge`, `claim_payment`, `patient_resp`
   - Claim Received Date → `claim_received_date`

3. **LINE DETAILS TABLE**:
   - Columns: Line Ctrl Nmbr | Dates of Service | Rend Prov ID | Rev | Sub Proc/Modifier/Units | Adjud Proc/Modifier/Units | Remark/Payer Code | Supp Info (AMT) | Charge | Adj (Qty) | Adj Amount | Payment
   - Each row → ServiceLine; parse supp_info_amt_code (e.g., 'B6') and supp_info_amt_value (e.g., 22.54) from 'Supp Info (AMT)' column
   - Adjustment codes and amounts: Extract ALL codes from 'Adj (Qty)' column and ALL amounts from 'Adj Amount' column
   - For EACH code-amount pair, create an AdjustmentDetail object with {code: 'OA-23', value: 137.46}
   - Store all pairs in `adjustment_codes_with_values` array to capture multiple adjustments per line
   - Example: Line with multiple adjustments → adjustment_codes_with_values: [{code: 'OA-23', value: 137.46}, {code: 'CO-45', value: 45.11}]

4. **SUPPLEMENTAL INFORMATION** line (e.g., 'Supplemental Information - AMT/Payer Codes: $29.14 (AU)') → `supplemental_info`

5. **CODE DESCRIPTIONS** (bottom):
   - REMARK CODE(S): code = description → `remark_codes` list
   - AMT CODE(S): code = description → `amt_codes` list
   - GROUP CODE(S): code = description → `group_codes` list
   - CLAIM ADJUSTMENT REASON CODE(S): code = description → `claim_adjustment_reason_codes` list
   - CLAIM STATUS CODE(S): code = description → `claim_status_codes` list

### KEY EXTRACTION RULES:
- Each 'Claim Summary' section = one ClaimModel; extract all fields.
- Supp Info (AMT) column: parse code and dollar value separately (e.g., '$22.54 (B6)' → code='B6', value=22.54).
- Parse all dollar amounts as floats (remove '$').
- Transaction Date appears top-right of Check Summary block.
- Each claim inherits payer/payee/check info from the Check Summary block.
"""


def section_builder(text: str) -> List[Dict[str, str]]:
    """Identify availity_bcbs_live claim block boundaries using regex on raw text."""
    import re
    sections = []

    pattern = r"(?:Patient\s+Name\s*:|Claim\s+Number\s*:)\s*([^\n]+)"
    claim_pattern = r"Claim\s+Number\s*:\s*([A-Z0-9]+)"
    matches = list(re.finditer(claim_pattern, text, re.IGNORECASE))

    if not matches:
        return [{"type": "content", "text": text}]

    for i, match in enumerate(matches):
        start_pos = match.start()
        end_pos = matches[i + 1].start() if i + 1 < len(matches) else len(text)

        sections.append({
            "type": "claim_block",
            "claim_number_hint": match.group(1).strip(),
            "text": text[start_pos:end_pos],
        })

    return sections


def calculate_totals(claims_data: dict) -> dict:
    """Calculate format-specific totals for the final availity_bcbs_live response."""
    total_charge = 0.0
    total_payment = 0.0
    total_patient_resp = 0.0
    total_adjustment = 0.0
    total_line_payment = 0.0

    claims = claims_data.get("claims") or []

    for claim in claims:
        total_charge += float(claim.get("claim_charge") or 0)
        total_payment += float(claim.get("claim_payment") or 0)
        total_patient_resp += float(claim.get("patient_resp") or 0)

        services = claim.get("services") or []
        for svc in services:
            total_adjustment += float(svc.get("adj_amount") or 0)
            total_line_payment += float(svc.get("payment") or 0)

    return {
        "total_charge": round(total_charge, 2),
        "total_payment": round(total_payment, 2),
        "total_patient_responsibility": round(total_patient_resp, 2),
        "total_adjustment": round(total_adjustment, 2),
        "total_line_payment": round(total_line_payment, 2),
    }