# Auto-generated format file for document type: instamed1
# Generated by FormatGeneratorAgent on 2026-03-06T13:09:03.253196

from __future__ import annotations
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, field_validator


class ServiceLineItem(BaseModel):
    """
    Represents an individual service line within an Instamed1 claim.
    Maps to each row in the claim's service table between the column headers and the 'Total' row.
    """

    begin_service_date: Optional[str] = Field(
        None,
        description="Start date of the service from the 'Service Dates' column in MM/DD/YYYY format (e.g., '9/28/2025')."
    )
    end_service_date: Optional[str] = Field(
        None,
        description="End date of the service from the 'Service Dates' column in MM/DD/YYYY format (e.g., '9/28/2025'). Usually the same as begin_service_date."
    )
    procedure_code: Optional[str] = Field(
        None,
        description="The CPT/HCPCS procedure code from the 'Procedure (Modifiers)' column (e.g., '92014', 'V2020', 'V2299', 'V2020', '92015')."
    )
    modifiers: Optional[str] = Field(
        None,
        description="Modifier(s) from the 'Procedure (Modifiers)' column, shown in parentheses after the code (e.g., 'NP', 'PL', 'MV', 'UL'). Separate multiple with a space."
    )
    num_of_units: Optional[int] = Field(
        None,
        description="Number of units from the 'No. of Units' column (e.g., 1, 2)."
    )
    amount_billed: Optional[float] = Field(
        None,
        description="Amount billed by the provider for this service line from the 'Amount Billed' column (e.g., 322.00, 125.00)."
    )
    allowed: Optional[float] = Field(
        None,
        description="Allowed/contractual amount from the 'Allowed' column per fee schedule (e.g., 87.50, 43.78, 0.00)."
    )
    payment: Optional[float] = Field(
        None,
        description="Amount paid by the payer for this service line from the 'Payment' column. May be negative for reversals (e.g., 0.00, -0.50, 37.00)."
    )
    patient_responsibility: Optional[float] = Field(
        None,
        description="Amount the patient is responsible for from the 'Patient Responsibility' column (e.g., 0.00, 10.00)."
    )
    contractual_adjustments: Optional[float] = Field(
        None,
        description="Contractual adjustment amount from the 'Contractual Adjustments' column (e.g., 322.00, 125.00, 163.00, 0.00)."
    )
    other_adjustments: Optional[float] = Field(
        None,
        description="Other adjustment amount from the 'Other Adjustments' column (e.g., 0.00)."
    )
    adjustment_reason: Optional[str] = Field(
        None,
        description="All adjustment reason codes from the 'Adjustment Reason' column (e.g., 'CO-45', 'PR-3 CO-45', 'CO-P14'). Separate multiple with a space."
    )
    remarks: Optional[str] = Field(
        None,
        description="Remark codes from the 'Remarks' column (e.g., 'N807'). Separate multiple with a space."
    )

    @field_validator("modifiers", "adjustment_reason", "remarks", mode="before")
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v


class ClaimModel(BaseModel):
    """
    Represents a full claim for a single patient within an Instamed1 remittance.
    Each claim block is identified by 'Claim / Patient Account # X for PATIENT_NAME'.
    """

    patient_account_number: Optional[str] = Field(
        None,
        description="Provider-assigned patient account number from the claim header (e.g., '0'). Often '0' if not assigned."
    )
    patient_name: Optional[str] = Field(
        None,
        description="Full name of the patient as shown in the claim header (e.g., 'MITCHEM, PAMELA P', 'VESTUTI, GINA M')."
    )
    insured_id: Optional[str] = Field(
        None,
        description="Insured member identification number shown in the 'Insured' row of the claim header (e.g., '601104537715', '601106698106')."
    )
    insured_name: Optional[str] = Field(
        None,
        description="Full name of the insured/subscriber from the 'Insured' row (e.g., 'MITCHEM, PAMELA P', 'VESTUTI, GINA M')."
    )
    payer_claim_number: Optional[str] = Field(
        None,
        description="Unique claim number assigned by the payer shown after 'Payer Claim #' in the claim header (e.g., '0046190797', '0046320261', '0046320175')."
    )
    claim_status: Optional[str] = Field(
        None,
        description="Processing status of the claim shown after 'Status' in the claim header (e.g., 'Processed as Primary')."
    )
    service_provider_npi: Optional[str] = Field(
        None,
        description="NPI of the service/rendering provider from the 'Service Provider' row (e.g., '1225069792')."
    )
    service_provider_qualifier: Optional[str] = Field(
        None,
        description="Qualifier code for the service provider identifier shown in parentheses (e.g., 'XX')."
    )
    service_provider_name: Optional[str] = Field(
        None,
        description="Name of the rendering/service provider from the 'Service Provider' row (e.g., 'Bigham, Kevin')."
    )

    @field_validator("claim_status", mode="before")
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v

    services: List[ServiceLineItem] = Field(
        default_factory=list,
        description="All individual service line items within this claim. Each row between the column headers and the 'Total' row."
    )
    claim_totals: Optional[ServiceLineItem] = Field(
        None,
        description=(
            "The 'Total' summary row at the bottom of each claim block. "
            "MANDATORY: Map the totals row here — do NOT include it in the services list. "
            "Contains summed values for Amount Billed, Allowed, Payment, Patient Responsibility, "
            "Contractual Adjustments, and Other Adjustments."
        )
    )


class ResponseModel(BaseModel):
    """
    Top-level response model for the Instamed1 remittance document.
    Matches the flat output of map_extracted_data directly.
    """

    payer_information: Optional[Dict[str, Any]] = Field(
        None,
        description="Payer name, ID, qualifier, and address from the PAYER INFORMATION block."
    )
    payment_information: Optional[Dict[str, Any]] = Field(
        None,
        description="Payment amount, date, method, trace number, and billing provider details from the PAYMENT INFORMATION block."
    )
    reconciliation_summary: Optional[Dict[str, Any]] = Field(
        None,
        description="High-level financial totals from the RECONCILIATION SUMMARY block."
    )
    claims: List[ClaimModel] = Field(
        default_factory=list,
        description="A comprehensive list of every patient claim extracted from the CLAIM SUMMARY section."
    )
    adjustment_reason_codes: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="All adjustment reason code definitions from the ADJUSTMENT REASON CODES table."
    )
    remark_codes: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="All remark code definitions from the REMARK CODES table."
    )


class BatchModel(BaseModel):
    """Model for validating a single batch of claims."""
    claims: List[ClaimModel] = Field(..., description="List of claims found in this batch")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Batch-level metadata")


def map_extracted_data(extracted_claims: List[dict], aggregated_metadata: dict) -> dict:
    """
    Maps raw AI extraction output into the final Instamed1 remittance hierarchy.
    The AI returns metadata as flat keys inside the BatchModel 'metadata' field,
    so we check both flat metadata and any nested wrapper key.
    """
    # The AI may nest data under a document-type key OR return it flat
    nested = aggregated_metadata.get("instamed1_remittance_page", {})
    if not isinstance(nested, dict):
        nested = {}

    # Merge: flat keys take precedence over any nested wrapper
    merged = {**nested, **aggregated_metadata}

    return {
        "payer_information": merged.get("payer_information"),
        "payment_information": merged.get("payment_information"),
        "reconciliation_summary": merged.get("reconciliation_summary"),
        "claims": extracted_claims,
        "adjustment_reason_codes": merged.get("adjustment_reason_codes") or [],
        "remark_codes": merged.get("remark_codes") or [],
    }


SCHEMA_DESCRIPTION = """
### HIERARCHICAL ANALYSIS METHODOLOGY:
**CRITICAL**: Study each page's visual hierarchy in detail before extraction:
1. **Scan for Summary Blocks**: Locate PAYER INFORMATION, PAYMENT INFORMATION, RECONCILIATION SUMMARY,
   and ADJUDICATION SUMMARY panels at the top of the document.
2. **Identify Claim Blocks**: Each claim block starts with a header row labeled
   'Claim / Patient Account # X for PATIENT_NAME'.
3. **Analyze Claim Structure**:
   - **Claim Header Row**: Shows Patient Account # and Patient Name in title.
   - **Insured Row**: Insured ID | Insured Name | Payer Claim # | Status
   - **Service Provider Row**: Service Provider NPI (qualifier) Provider Name
   - **Column Header Row**: Service Dates | Procedure (Modifiers) | No. of Units | Amount Billed |
     Allowed | Payment | Patient Responsibility | Contractual Adjustments | Other Adjustments |
     Adjustment Reason | Remarks
   - **Service Lines**: Every data row between the column headers and the 'Total' row.
   - **Total Row**: The 'Total' row at the bottom of each claim — MANDATORY: map to `claim_totals`, NEVER into `services`.
4. **Capture Code Tables**: Extract all rows from ADJUSTMENT REASON CODES and REMARK CODES tables at the bottom.

### INSTAMED1 DOCUMENT STRUCTURE:

1. **PAYER INFORMATION BLOCK** (top-left panel):
   - Payer Name (e.g., 'Superior Vision by MetLife')
   - Payer ID with qualifier in parentheses (e.g., '13374 (XV)')
   - Payer Address (e.g., '881 Elkridge Landing Rd, Linthicum Heights, MD 21090')
   Map to `payer_information`: { payer_name, payer_id, payer_id_qualifier, payer_address }

2. **PAYMENT INFORMATION BLOCK** (bottom-left panel):
   - Payment Amount (e.g., $8.50)
   - Payment Date (e.g., '10/15/2025')
   - Payment Method (e.g., 'ACH')
   - Check/EFT Trace # (e.g., '39521379')
   - Billing Provider Name (e.g., 'FIRST CHOICE EYE CARE OD FLLC')
   - Billing Provider ID with qualifier (e.g., '300095616 (FI)')
   - Billing Provider Address (e.g., '14617A W Lawyers Rd, MATTHEWS, NC 281043219')
   - Version Identification (e.g., 'HSP')
   Map to `payment_information`: { payment_amount, payment_date, payment_method,
   check_eft_trace_number, billing_provider_name, billing_provider_id,
   billing_provider_id_qualifier, billing_provider_address, version_identification }

3. **RECONCILIATION SUMMARY BLOCK** (top-center panel):
   - Total Charges (e.g., $1,657.00)
   - Total Patient Responsibility (e.g., ($20.00) — may be negative)
   - Total Contractual Adjustments (e.g., ($1,628.50) — may be negative)
   - Total Other Adjustments (e.g., ($0.00))
   - Total Claim Payment (e.g., $8.50)
   - Provider Adjustments (e.g., $0.00)
   - Payment Amount (e.g., $8.50)
   Map to `reconciliation_summary`: { total_charges, total_patient_responsibility,
   total_contractual_adjustments, total_other_adjustments, total_claim_payment,
   provider_adjustments, payment_amount }

4. **CLAIM SUMMARY SECTION** — labeled 'CLAIM SUMMARY (N)' where N is the count:

   Each claim block structure:
   a. **Claim Title Row**: 'Claim / Patient Account # {account_number} for {PATIENT_NAME}'
      → `patient_account_number`, `patient_name`
   b. **Insured Row**: '{insured_id} {INSURED_NAME} Payer Claim # {payer_claim_number} Status {claim_status}'
      → `insured_id`, `insured_name`, `payer_claim_number`, `claim_status`
   c. **Service Provider Row**: '{npi} ({qualifier}) {provider_name}'
      → `service_provider_npi`, `service_provider_qualifier`, `service_provider_name`
   d. **Column Headers**: Service Dates | Procedure (Modifiers) | No. of Units | Amount Billed |
      Allowed | Payment | Patient Responsibility | Contractual Adjustments | Other Adjustments |
      Adjustment Reason | Remarks
   e. **Service Line Rows**: One row per service (extract ALL rows before 'Total'):
      - begin_service_date / end_service_date: from 'Service Dates' column (e.g., '9/28/2025 - 9/28/2025')
      - procedure_code: base CPT/HCPCS code (e.g., 'V2020', '92014', 'V2299', '92015')
      - modifiers: content in parentheses after procedure code (e.g., 'NP', 'PL', 'MV', 'UL')
      - num_of_units: integer from 'No. of Units' column (e.g., 1, 2)
      - amount_billed: float from 'Amount Billed' column (e.g., 322.00, 125.00)
      - allowed: float from 'Allowed' column (e.g., 87.50, 43.78, 0.00)
      - payment: float from 'Payment' column — may be negative (e.g., 0.00, -0.50, 37.00)
      - patient_responsibility: float from 'Patient Responsibility' column (e.g., 0.00, 10.00)
      - contractual_adjustments: float from 'Contractual Adjustments' column (e.g., 322.00, 163.00)
      - other_adjustments: float from 'Other Adjustments' column (e.g., 0.00)
      - adjustment_reason: space-separated codes from 'Adjustment Reason' column (e.g., 'CO-45', 'PR-3 CO-45', 'CO-P14')
      - remarks: space-separated codes from 'Remarks' column (e.g., 'N807')
   f. **Total Row**: Labeled 'Total' — MANDATORY: map to `claim_totals`. NEVER add to `services`.

5. **ADJUSTMENT REASON CODES TABLE** (below claim blocks):
   Columns: Code | Adjustment Reason | Description
   Groups: 'CO: Contractual Obligations', 'PR: Patient Responsibility'
   Extract all rows into `adjustment_reason_codes`:
   [{ "group": "CO: Contractual Obligations", "code": "CO-45", "description": "..." }, ...]

6. **REMARK CODES TABLE** (below adjustment codes):
   Columns: Code | Description
   Extract all rows into `remark_codes`:
   [{ "code": "N807", "description": "..." }, ...]

### FIELD EXTRACTION NOTES:

- **Service Dates column**: Contains date range 'MM/DD/YYYY - MM/DD/YYYY'.
  Split on ' - ' → begin_service_date and end_service_date.
- **Procedure (Modifiers) column**: Contains code + modifier in parentheses.
  Example: 'V2020(NP)' → procedure_code='V2020', modifiers='NP'.
  Example: 'V2744(MV)' → procedure_code='V2744', modifiers='MV'.
  Example: '92014' (no modifier) → procedure_code='92014', modifiers=null.
- **Payment column**: Can be negative (e.g., -$0.50 → -0.50, -$15.00 → -15.00).
- **Patient Responsibility column**: Stacked rows may show two values for two service lines.
  Map each value to the correct service line by vertical position.
- **Contractual Adjustments column**: May have two stacked values (e.g., '$0.00 / $163.00').
  Map to respective service lines.
- **Adjustment Reason column**: May show multiple codes stacked (e.g., 'PR-3' on line 1, 'CO-45' on line 2).
  When both apply to a single service line, join as 'PR-3 CO-45'.
- **Insured ID format**: Numeric string (e.g., '601104537715'). Always treat as string.
- **Payer Claim # format**: Numeric string (e.g., '0046190797'). Always treat as string.

### ZERO DATA LOSS RULES:
- Every claim MUST have `claim_totals`. Retrieve from the 'Total' row at bottom of each claim block.
- Multi-row stacked cells: When Payment, Patient Responsibility, Contractual Adjustments, or
  Adjustment Reason shows stacked values, split them across correct service lines by vertical position.
- `adjustment_reason` must capture ALL codes per service line, space-separated (e.g., 'PR-3 CO-45').
- `adjustment_reason_codes` and `remark_codes` tables must be fully extracted — never return empty
  lists if entries are visible.
- `reconciliation_summary` is MANDATORY when the RECONCILIATION SUMMARY block is present.
- Service lines showing $0.00 in payment must still be included in `services`.
- All three claim blocks in CLAIM SUMMARY (3) must be extracted — do not skip any claim.
"""


def section_builder(text: str) -> List[Dict[str, str]]:
    """
    Identify Instamed1 claim block boundaries using regex on raw text.
    Each claim starts with 'Claim / Patient Account #'.
    """
    import re
    sections = []

    pattern = r"Claim\s*/\s*Patient\s+Account\s+#\s*(\S+)\s+for\s+([A-Z ,.']+)"
    matches = list(re.finditer(pattern, text, re.IGNORECASE))

    if not matches:
        return [{"type": "content", "text": text}]

    for i, match in enumerate(matches):
        start_pos = match.start()
        end_pos = matches[i + 1].start() if i + 1 < len(matches) else len(text)

        sections.append({
            "type": "claim_block",
            "account_number_hint": match.group(1).strip(),
            "patient_hint": match.group(2).strip(),
            "text": text[start_pos:end_pos],
        })

    return sections


def calculate_totals(claims_data: dict) -> dict:
    """Calculate format-specific totals for the final Instamed1 response."""
    total_billed = 0.0
    total_payment = 0.0
    total_patient_responsibility = 0.0
    total_contractual_adjustments = 0.0

    # claims is at top level (flat dict from map_extracted_data)
    claims = (
        claims_data.get("claims")
        or claims_data.get("instamed1_remittance_page", {}).get("claims")
        or []
    )

    for claim in claims:
        services = claim.get("services", [])
        for svc in services:
            total_billed += float(svc.get("amount_billed") or 0)
            total_payment += float(svc.get("payment") or 0)
            total_patient_responsibility += float(svc.get("patient_responsibility") or 0)
            total_contractual_adjustments += float(svc.get("contractual_adjustments") or 0)

    return {
        "total_billed": round(total_billed, 2),
        "total_payment": round(total_payment, 2),
        "total_patient_responsibility": round(total_patient_responsibility, 2),
        "total_contractual_adjustments": round(total_contractual_adjustments, 2),
    }
