# Auto-generated format file for document type: ocrfax
# Generated by FormatGeneratorAgent on 2026-03-11T14:33:54.562071

from __future__ import annotations
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, field_validator


class ServiceLineItem(BaseModel):
    """
    Represents an individual service line within an OCR/Fax Virtual Card Payment remittance claim.
    Maps to each row in the claim's service table.
    """

    service_date: Optional[str] = Field(
        None,
        description="Date of service from the 'Service Date' column in MM/DD/YY format (e.g., '09/16/25', '07/16/25', '07/30/25', '07/31/25')."
    )
    proc_rev_code: Optional[str] = Field(
        None,
        description="The CPT/HCPCS procedure or revenue code from the 'Proc/Rev Code' column (e.g., '92014', '92004', '92015', '92250', '99012')."
    )
    modifiers: Optional[str] = Field(
        None,
        description="Modifier(s) from the '(Modifiers)' column (e.g., '160', '26, EXC7', 'EXC7', '1045, 23', '15, EXGB', 'JXCOR', 'EXC7, PXGB', '160, EXGB', '23, EXC7, PXGB'). Separate multiple with a space."
    )
    explanation_codes: Optional[str] = Field(
        None,
        description="Explanation code(s) from the 'Explanation Code(s)' column. Separate multiple with a space."
    )
    units: Optional[int] = Field(
        None,
        description="Number of units from the 'Units' column. May be negative (e.g., -1, 1)."
    )
    total_charge: Optional[float] = Field(
        None,
        description="Total charge amount from the 'Total Charge' column. May be negative for reversals (e.g., -186.00, 186.00, -335.00, 35.00, -598.00, 98.00, -142.00, 142.00)."
    )
    allowed_amount: Optional[float] = Field(
        None,
        description="Allowed amount from the 'Allowed Amount' column (e.g., 0.00, 116.83, 190.75, 82.32)."
    )
    provider_discount: Optional[float] = Field(
        None,
        description="Provider discount amount from the 'Provider Discount' column. May be negative (e.g., -186.00, -335.00, -598.00, -192.00, -151.16, -190.75, -169.25, -82.32)."
    )
    other_plan_payment: Optional[float] = Field(
        None,
        description="Other plan payment amount from the 'Other Plan Payment' column (e.g., 0.00)."
    )
    other_adjustment: Optional[float] = Field(
        None,
        description="Other adjustment amount from the 'Other Adjustment' column (e.g., 0.00)."
    )
    coinsurance: Optional[float] = Field(
        None,
        description="Coinsurance amount from the 'Patient Obligation - Coinsurance' column (e.g., 0.00)."
    )
    copay: Optional[float] = Field(
        None,
        description="Copay amount from the 'Patient Obligation - Copay' column (e.g., 0.00, 50.00, 60.00, 100.00)."
    )
    deductible: Optional[float] = Field(
        None,
        description="Deductible amount from the 'Patient Obligation - Deductible' column (e.g., 0.00)."
    )
    non_covered: Optional[float] = Field(
        None,
        description="Non-covered amount from the 'Patient Obligation - Non-Covered' column (e.g., 0.00)."
    )
    net_payment_amount: Optional[float] = Field(
        None,
        description="Net payment amount from the 'Net Payment Amount' column (e.g., 0.00, 66.83, -0.00, 34.33, 101.16, 56.83, 16.83, 18.09, 34.33, 51.16)."
    )

    @field_validator("modifiers", "explanation_codes", mode="before")
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v


class ClaimModel(BaseModel):
    """
    Represents a full claim for a single patient within an OCR/Fax Virtual Card Payment remittance.
    Each claim block is identified by 'Claim Number:' and 'Patient Name:' headers.
    """

    claim_number: Optional[str] = Field(
        None,
        description="Unique claim number from 'Claim Number:' label (e.g., '20250922009737', '20250822018479', '20250803006396', '20250803013009', '20250803006395')."
    )
    group_id: Optional[str] = Field(
        None,
        description="Group ID from 'Group ID:' label (e.g., 'HJM02001', 'HJM02001', '06946001', '06946001', '06946001', '52A010')."
    )
    patient_name: Optional[str] = Field(
        None,
        description="Full name of the patient from 'Patient Name:' label (e.g., 'Michele Dombo', 'Jose Velasquez', 'JOANIE WEHBA', 'HUDSON WEHBA', 'PHYLLIS WILBURN', 'ROSEMARY HERNANDEZ')."
    )
    patient_acct_number: Optional[str] = Field(
        None,
        description="Patient account number from 'Patient Acct #:' label (e.g., '83894', '83103', '83100', '83143', '82833')."
    )
    reference_number: Optional[str] = Field(
        None,
        description="Reference Number from 'Reference Number:' label (e.g., '5974547')."
    )
    subscriber_name: Optional[str] = Field(
        None,
        description="Name of the subscriber/insured from 'Subscriber Name:' label (e.g., 'Morgan Dombo', 'Frances Velasquez', 'KELLY WEHBA', 'PHYLLIS WILBURN', 'ROSEMARY HERNANDEZ')."
    )
    subscriber_id: Optional[str] = Field(
        None,
        description="Subscriber ID from 'Subscriber ID:' label (e.g., 'BSW120009000', 'BSW116696200', '100106272800', '100272700', '10007121200')."
    )
    network: Optional[str] = Field(
        None,
        description="Network identifier shown under 'Network:' label (e.g., the network type for this claim)."
    )
    provider_name: Optional[str] = Field(
        None,
        description="Name of the rendering/billing provider from 'Provider:' label (e.g., '1558478461-Shelda M Shaffer')."
    )

    services: List[ServiceLineItem] = Field(
        default_factory=list,
        description="All individual service line items within this claim. Each data row between column headers and the 'Claim Totals' row."
    )
    claim_totals: Optional[ServiceLineItem] = Field(
        None,
        description=(
            "The 'Claim Totals' summary row for this claim. "
            "MANDATORY: Map the totals row here — do NOT include it in the services list. "
            "Contains summed values for Total Charge, Allowed Amount, Provider Discount, "
            "Other Plan Payment, Other Adjustment, Coinsurance, Copay, Deductible, Non-Covered, Net Payment Amount."
        )
    )


class StatementSummary(BaseModel):
    """
    Represents the Statement Summary block at the bottom of the remittance document.
    """

    total_charge: Optional[float] = Field(
        None,
        description="Grand total charge across all claims from the 'Statement Summary - Total Charge' column (e.g., 0.00)."
    )
    allowed_amount: Optional[float] = Field(
        None,
        description="Grand total allowed amount from the 'Statement Summary - Allowed Amount' column (e.g., 861.47)."
    )
    provider_discount: Optional[float] = Field(
        None,
        description="Grand total provider discount from the 'Statement Summary - Provider Discount' column (e.g., -861.47)."
    )
    other_plan_payment: Optional[float] = Field(
        None,
        description="Grand total other plan payment from the 'Statement Summary - Other Plan Payment' column (e.g., 0.00)."
    )
    other_adjustments: Optional[float] = Field(
        None,
        description="Grand total other adjustments from the 'Statement Summary - Other Adjustments' column (e.g., 0.00)."
    )
    patient_obligation: Optional[float] = Field(
        None,
        description="Grand total patient obligation from the 'Statement Summary - Patient Obligation' column (e.g., 470.41)."
    )
    net_payment_amount: Optional[float] = Field(
        None,
        description="Grand total net payment amount from the 'Statement Summary - Net Payment Amount' column (e.g., 391.06)."
    )


class DocumentTotal(BaseModel):
    """
    Represents the Document Total section at the bottom right of the remittance.
    """

    net_payment_amount: Optional[float] = Field(
        None,
        description="Net Payment Amount from 'Document Total - Net Payment Amount:' (e.g., 391.06)."
    )
    payment_adjustments: Optional[float] = Field(
        None,
        description="Payment Adjustments from 'Document Total - Payment Adjustments:' (e.g., 0.00)."
    )
    total_payment: Optional[float] = Field(
        None,
        description="Total Payment from 'Document Total - Total Payment:' (e.g., 391.06)."
    )


class ResponseModel(BaseModel):
    """
    Top-level response model for the OCR/Fax Virtual Card Payment (QuicRemit/Electronic Payment Clearinghouse) remittance document.
    Matches the flat output of map_extracted_data directly.
    """

    # Document-level header fields
    payer_name: Optional[str] = Field(
        None,
        description="Name of the payer/sender (e.g., 'Electronic Payment Clearinghouse', 'Baylor Scott & White Health Plan')."
    )
    payer_address: Optional[str] = Field(
        None,
        description="Payer mailing address (e.g., '1206 West Campus Dr., Temple, TX 76502')."
    )
    payee_name: Optional[str] = Field(
        None,
        description="Name of the payee/provider practice (e.g., 'WILKINSON AND SHAFFER PC')."
    )
    payee_address: Optional[str] = Field(
        None,
        description="Payee mailing address (e.g., 'PO BOX 108, SWEETWATER TX 79556')."
    )
    fax_from: Optional[str] = Field(
        None,
        description="Fax sender information from 'From:' header (e.g., 'Virtual Card Payment  Fax: +14402972748')."
    )
    fax_to: Optional[str] = Field(
        None,
        description="Fax recipient information from 'To:' header (e.g., 'WILKINSON AND SHAFFER IFax: +13252358326')."
    )
    received_date: Optional[str] = Field(
        None,
        description="Date/time the fax was received as shown at the top of the document (e.g., '01/17/2026 09:07AM')."
    )
    tran_nbr: Optional[str] = Field(
        None,
        description="Transaction number from 'Tran Nbr:' label (e.g., '391321447')."
    )
    card_value: Optional[float] = Field(
        None,
        description="Virtual card value from 'Card Value:' label (e.g., 391.06)."
    )
    payment_date: Optional[str] = Field(
        None,
        description="Payment date from 'Date:' label (e.g., '01/16/2026')."
    )
    virtual_card_account_number: Optional[str] = Field(
        None,
        description="Virtual card account number (e.g., '5328 6410 5928 6844')."
    )
    cvv: Optional[str] = Field(
        None,
        description="CVV code from the virtual card (e.g., '989')."
    )
    good_thru: Optional[str] = Field(
        None,
        description="Card expiry/good thru date from the virtual card (e.g., '04/26')."
    )
    tax_id: Optional[str] = Field(
        None,
        description="Tax ID from 'Tax ID:' label at the top of the remittance table (e.g., '201674251')."
    )
    epc_draft_number: Optional[str] = Field(
        None,
        description="EPC Draft # from 'EPC Draft #:' label (e.g., '391321447')."
    )
    payment_week: Optional[str] = Field(
        None,
        description="Payment week number from 'Payment Week:' label (e.g., '2')."
    )
    payment_date_table: Optional[str] = Field(
        None,
        description="Payment date as shown in the remittance table header from 'Payment Date:' label (e.g., '01/16/2026')."
    )
    claims: List[ClaimModel] = Field(
        default_factory=list,
        description="A comprehensive list of every patient claim extracted from the document."
    )
    statement_summary: Optional[StatementSummary] = Field(
        None,
        description="The Statement Summary block at the bottom of the remittance showing grand totals."
    )
    document_total: Optional[DocumentTotal] = Field(
        None,
        description="The Document Total block showing Net Payment Amount, Payment Adjustments, and Total Payment."
    )


class BatchModel(BaseModel):
    """Model for validating a single batch of claims."""
    claims: List[ClaimModel] = Field(..., description="List of claims found in this batch")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Batch-level metadata")


def map_extracted_data(extracted_claims: List[dict], aggregated_metadata: dict) -> dict:
    """
    Maps raw AI extraction output into the final ocrfax remittance hierarchy.
    The AI returns metadata as flat keys inside the BatchModel 'metadata' field.
    """
    # The AI may nest data under a document-type key OR return it flat
    nested = aggregated_metadata.get("ocrfax_remittance_page", {})
    if not isinstance(nested, dict):
        nested = {}

    # Merge: flat keys take precedence over any nested wrapper
    merged = {**nested, **aggregated_metadata}

    return {
        "payer_name": merged.get("payer_name"),
        "payer_address": merged.get("payer_address"),
        "payee_name": merged.get("payee_name"),
        "payee_address": merged.get("payee_address"),
        "fax_from": merged.get("fax_from"),
        "fax_to": merged.get("fax_to"),
        "received_date": merged.get("received_date"),
        "tran_nbr": merged.get("tran_nbr"),
        "card_value": merged.get("card_value"),
        "payment_date": merged.get("payment_date"),
        "virtual_card_account_number": merged.get("virtual_card_account_number"),
        "cvv": merged.get("cvv"),
        "good_thru": merged.get("good_thru"),
        "tax_id": merged.get("tax_id"),
        "epc_draft_number": merged.get("epc_draft_number"),
        "payment_week": merged.get("payment_week"),
        "payment_date_table": merged.get("payment_date_table"),
        "claims": extracted_claims,
        "statement_summary": merged.get("statement_summary"),
        "document_total": merged.get("document_total"),
    }


SCHEMA_DESCRIPTION = """
### HIERARCHICAL ANALYSIS METHODOLOGY:
**CRITICAL**: Study each page's visual hierarchy in detail before extraction:
1. **Scan the Fax/Document Header**: Top section contains fax routing info (From/To), received timestamp,
   payer info (Electronic Payment Clearinghouse / Baylor Scott & White Health Plan), payee info
   (WILKINSON AND SHAFFER PC), and QuicRemit virtual card details (Tran Nbr, Card Value, Date,
   Account Number, CVV, Good Thru).
2. **Scan the Remittance Table Header**: Identifies Tax ID, EPC Draft #, Payment Week, Payment Date, Page X of Y.
3. **Identify Claim Blocks**: Each claim block starts with 'Claim Number:' and 'Group ID:' header rows,
   followed by 'Patient Name:', 'Patient Acct #:', 'Reference Number:', 'Subscriber Name:', 'Subscriber ID:'.
4. **Extract Service Lines**: Rows between the column headers and the 'Claim Totals' row.
5. **Map Claim Totals**: The 'Claim Totals' row — MANDATORY: map to `claim_totals`, NEVER into `services`.
6. **Capture Statement Summary**: Grand totals table at the bottom of the last page.
7. **Capture Document Total**: Net Payment Amount, Payment Adjustments, Total Payment at the bottom right.

### OCRFAX DOCUMENT STRUCTURE:

1. **FAX/DOCUMENT HEADER** (top of every page):
   - From: Virtual Card Payment  Fax: +14402972748
   - To: WILKINSON AND SHAFFER IFax: +13252358326
   - Received: 01/17/2026 09:07AM (top right)
   - Page X of Y (top right)
   - Payer: Electronic Payment Clearinghouse / Baylor Scott & White Health Plan / 1206 West Campus Dr. / Temple, TX 76502
   - Payee: WILKINSON AND SHAFFER PC / PO BOX 108 / SWEETWATER TX 79556
   - QuicRemit Virtual Card box: Tran Nbr, Card Value, Date, Account Number, CVV, Good Thru

2. **REMITTANCE TABLE HEADER** (one per document, at top of first table):
   - Tax ID: 201674251
   - EPC Draft #: 391321447
   - Payment Week: 2
   - Payment Date: 01/16/2026
   - Page X of Y

3. **CLAIM BLOCKS** (repeating, one per patient):
   Each claim block contains:
   a. **Claim Header Row**:
      - Claim Number: (e.g., '20250922009737')
      - Group ID: (e.g., 'HJM02001')
      - Reference Number: (e.g., '5974547')
      - Subscriber Name: (e.g., 'Morgan Dombo')
   b. **Provider Row**:
      - Provider: (e.g., '1558478461-Shelda M Shaffer')
      - Patient Name: (e.g., 'Michele Dombo')
      - Subscriber ID: (e.g., 'BSW120009000')
   c. **Network Row**:
      - Network: (e.g., label under 'Network:')
      - Patient Acct #: (e.g., '83894')
   d. **Column Headers**:
      Service Date | Proc/Rev Code (Modifiers) | Explanation Code(s) | Units | Total Charge |
      Allowed Amount | Provider Discount | Other Plan Payment | Other Adjustment |
      Patient Obligation [Coinsurance | Copay | Deductible | Non-Covered] | Net Payment Amount
   e. **Service Line Rows** (extract ALL rows before 'Claim Totals'):
      - service_date: from 'Service Date' column (e.g., '09/16/25', '07/16/25', '07/30/25')
      - proc_rev_code: CPT/HCPCS code from 'Proc/Rev Code' part (e.g., '92014', '92004', '92015', '92250', '92012')
      - modifiers: modifier(s) from '(Modifiers)' sub-column (e.g., '160', '26, EXC7', 'EXC7',
        '1045, 23', '15, EXGB', 'JXCOR', 'EXC7, PXGB', '160, EXGB', '23, EXC7, PXGB').
        Note: modifiers can be numeric (e.g., '160') or alphanumeric codes.
      - explanation_codes: from 'Explanation Code(s)' column — null if blank.
      - units: integer from 'Units' column. Negative values (e.g., -1) indicate reversal lines.
      - total_charge: float from 'Total Charge' column. Negative for reversal lines (e.g., -186.00).
      - allowed_amount: float from 'Allowed Amount' column (e.g., 0.00, 116.83, 138.33, 190.75).
      - provider_discount: float from 'Provider Discount' column. Usually negative (e.g., -186.00, -335.00).
      - other_plan_payment: float from 'Other Plan Payment' column (e.g., 0.00).
      - other_adjustment: float from 'Other Adjustment' column (e.g., 0.00).
      - coinsurance: float from 'Patient Obligation - Coinsurance' sub-column (e.g., 0.00).
      - copay: float from 'Patient Obligation - Copay' sub-column (e.g., 0.00, 50.00, 60.00, 100.00).
      - deductible: float from 'Patient Obligation - Deductible' sub-column (e.g., 0.00).
      - non_covered: float from 'Patient Obligation - Non-Covered' sub-column (e.g., 0.00).
      - net_payment_amount: float from 'Net Payment Amount' column (e.g., 0.00, 66.83, 34.33, 101.16).
   f. **Claim Totals Row**: Labeled with 'Claim Totals:' — MANDATORY: map to `claim_totals`.
      NEVER add this row to the `services` list.

4. **STATEMENT SUMMARY** (bottom of last page):
   Columns: Total Charge | Allowed Amount | Provider Discount | Other Plan Payment | Other Adjustments |
   Patient Obligation | Net Payment Amount
   Extract into `statement_summary`.

5. **DOCUMENT TOTAL** (bottom right of last page):
   - Net Payment Amount: (e.g., $391.06)
   - Payment Adjustments: (e.g., $0.00)
   - Total Payment: (e.g., $391.06)
   Extract into `document_total`.

### REVERSAL/NEGATIVE LINE HANDLING:
Some claims contain paired lines: a negative reversal line (units = -1, total_charge negative)
followed by a positive correction line (units = 1, total_charge positive).
Both lines MUST be extracted into `services`. Do not skip negative lines.
Examples:
  - units=-1, total_charge=-186.00, allowed_amount=0.00, net_payment_amount=0.00
  - units=1, total_charge=186.00, allowed_amount=116.83, net_payment_amount=66.83

### FIELD EXTRACTION NOTES:
- **Proc/Rev Code and Modifiers**: The column header is 'Proc/Rev Code (Modifiers)'.
  The procedure code (e.g., '92014') appears first; modifiers (e.g., '160', '26, EXC7') appear
  in a sub-column or stacked below/alongside. Capture each separately.
- **Patient Obligation columns**: Split into four sub-columns: Coinsurance | Copay | Deductible | Non-Covered.
  Extract each independently.
- **Copay values**: Common non-zero values are 50.00, 60.00, 100.00. These represent patient responsibility.
- **Total Charge**: May be negative for reversal lines. Strip any currency signs and parse as float.
- **Net Payment Amount**: The actual amount paid to the provider for that line.
- **Virtual Card Account Number**: Appears in the QuicRemit box as '5328 6410 5928 6844' — capture with spaces.
- **Provider field**: Contains NPI-ProviderName format (e.g., '1558478461-Shelda M Shaffer').
- **Subscriber ID formats vary**: May be alphanumeric (e.g., 'BSW120009000', 'BSW116696200', '100106272800').
- **Claim Number format**: Long numeric string (e.g., '20250922009737', '20250803006396').
- **Reference Number**: Shorter numeric string (e.g., '5974547') — different from Claim Number.
- **Group ID**: Alphanumeric (e.g., 'HJM02001', '06946001', '52A010').

### ZERO DATA LOSS RULES:
- Every claim MUST have `claim_totals`. Retrieve from the 'Claim Totals' row.
- ALL service lines per claim must be extracted — including negative/reversal lines.
- `statement_summary` is MANDATORY when the Statement Summary table is present.
- `document_total` is MANDATORY when the Document Total section is present.
- Copay amounts must be captured per service line — do not zero out non-zero copay values.
- ALL claim blocks across ALL pages must be extracted — never skip a claim.
- Negative total_charge values must be preserved with their negative sign.
- Net payment amounts of 0.00 must still be captured (not null).
- The virtual card details (account number, CVV, good thru) must be extracted from the QuicRemit box.
"""


def section_builder(text: str) -> List[Dict[str, str]]:
    """
    Identify ocrfax claim block boundaries using regex on raw text.
    Each claim starts with 'Claim Number:'.
    """
    import re
    sections = []

    pattern = r"Claim\s+Number[:\s]+(\d+)"
    matches = list(re.finditer(pattern, text, re.IGNORECASE))

    if not matches:
        return [{"type": "content", "text": text}]

    for i, match in enumerate(matches):
        start_pos = match.start()
        end_pos = matches[i + 1].start() if i + 1 < len(matches) else len(text)

        sections.append({
            "type": "claim_block",
            "claim_number_hint": match.group(1).strip(),
            "text": text[start_pos:end_pos],
        })

    return sections


def calculate_totals(claims_data: dict) -> dict:
    """Calculate format-specific totals for the final ocrfax response."""
    total_charge = 0.0
    total_net_payment = 0.0
    total_patient_copay = 0.0
    total_coinsurance = 0.0

    # claims is at top level (flat dict from map_extracted_data)
    claims = (
        claims_data.get("claims")
        or claims_data.get("ocrfax_remittance_page", {}).get("claims")
        or []
    )

    for claim in claims:
        services = claim.get("services", [])
        for svc in services:
            total_charge += float(svc.get("total_charge") or 0)
            total_net_payment += float(svc.get("net_payment_amount") or 0)
            total_patient_copay += float(svc.get("copay") or 0)
            total_coinsurance += float(svc.get("coinsurance") or 0)

    return {
        "total_charge": round(total_charge, 2),
        "total_net_payment": round(total_net_payment, 2),
        "total_patient_copay": round(total_patient_copay, 2),
        "total_coinsurance": round(total_coinsurance, 2),
    }