# Auto-generated format file for document type: ocrfax2
# Generated by FormatGeneratorAgent on 2026-03-11T18:30:54.734542

# Auto-generated format file for document type: ocrfax2
# Generated by FormatGeneratorAgent

from __future__ import annotations
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, field_validator


class ServiceLineItem(BaseModel):
    service_date: Optional[str] = Field(None, description="Date of service from 'Service Date' column (e.g., '09/16/25', '07/16/25', '07/30/25', '08/19/25').")
    proc_rev_code: Optional[str] = Field(None, description="CPT/HCPCS procedure code from 'Proc/Rev Code' column (e.g., '92014', '92004', '92015', '92250', '92012').")
    modifiers: Optional[str] = Field(None, description="Modifier(s) from '(Modifiers)' sub-column (e.g., '160', '26, EXC7', '1045, 23', '15, EXGB', 'BXC7, EXGB', '23, RXC7, HXGB').")
    explanation_codes: Optional[str] = Field(None, description="Explanation code(s) from 'Explanation Code(s)' column. Null if blank.")
    units: Optional[int] = Field(None, description="Number of units from 'Units' column. May be negative (e.g., -1, 1).")
    total_charge: Optional[float] = Field(None, description="Total charge from 'Total Charge' column. Negative for reversal lines (e.g., -186.00, 186.00, -35.00, 35.00, -98.00, 98.00).")
    allowed_amount: Optional[float] = Field(None, description="Allowed amount from 'Allowed Amount' column (e.g., 0.00, 116.83, 138.33, 34.33, 82.32).")
    provider_discount: Optional[float] = Field(None, description="Provider discount from 'Provider Discount' column. Usually negative (e.g., -186.00, 69.17, -35.00, -98.00).")
    other_plan_payment: Optional[float] = Field(None, description="Other plan payment from 'Other Plan Payment' column (e.g., 0.00).")
    other_adjustment: Optional[float] = Field(None, description="Other adjustment from 'Other Adjustment' column (e.g., 0.00).")
    coinsurance: Optional[float] = Field(None, description="Coinsurance from 'Patient Obligation - Coinsurance' sub-column (e.g., 0.00).")
    copay: Optional[float] = Field(None, description="Copay from 'Patient Obligation - Copay' sub-column (e.g., 0.00, 50.00, 60.00, 100.00).")
    deductible: Optional[float] = Field(None, description="Deductible from 'Patient Obligation - Deductible' sub-column (e.g., 0.00).")
    non_covered: Optional[float] = Field(None, description="Non-covered from 'Patient Obligation - Non-Covered' sub-column (e.g., 0.00).")
    net_payment_amount: Optional[float] = Field(None, description="Net payment from 'Net Payment Amount' column (e.g., 0.00, 66.83, 34.33, 56.83, 130.75, 51.16).")

    @field_validator("modifiers", "explanation_codes", mode="before")
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v


class ClaimModel(BaseModel):
    claim_number: Optional[str] = Field(None, description="Claim number from 'Claim Number:' label (e.g., '20250922009737', '20250722015531', '20250822018479', '20250803006396', '20250803013009', '20250803006395').")
    group_id: Optional[str] = Field(None, description="Group ID from 'Group ID:' label (e.g., 'HJM02001', '52A010', '06946001').")
    patient_name: Optional[str] = Field(None, description="Patient name from 'Patient Name:' label (e.g., 'Michele Domaho', 'ROSEMARY HERNANDEZ', 'Jose Velasquez', 'JOANIE WEHBA', 'HUDSON WEHBA', 'PHYLLIS WILBURN').")
    patient_acct_number: Optional[str] = Field(None, description="Patient account number from 'Patient Acct #:' label (e.g., '83894', '82833', '83453', '83103', '83100', '83143').")
    reference_number: Optional[str] = Field(None, description="Reference number from 'Reference Number:' label (e.g., '5974547').")
    subscriber_name: Optional[str] = Field(None, description="Subscriber name from 'Subscriber Name:' label (e.g., 'Morgan Donahue', 'ROSEMARY HERNANDEZ', 'Frances Velasquez', 'KELLY WEHBA', 'PHYLLIS WILBURN').")
    subscriber_id: Optional[str] = Field(None, description="Subscriber ID from 'Subscriber ID:' label (e.g., 'BSW120009000', '100071121200', 'BSW116696200', '100106272800', '100106272700').")
    network: Optional[str] = Field(None, description="Network identifier from 'Network:' label.")
    provider_name: Optional[str] = Field(None, description="Provider from 'Provider:' label (e.g., '1558478461-Shelda M Shaffer').")
    services: List[ServiceLineItem] = Field(default_factory=list, description="All service line rows between column headers and 'Claim Total' row.")
    claim_totals: Optional[ServiceLineItem] = Field(None, description="The 'Claim Total' summary row. MANDATORY: map here, NEVER into services list.")


class StatementSummary(BaseModel):
    total_charge: Optional[float] = Field(None, description="Grand total charge from 'Statement Summary - Total Charge' column (e.g., 0.00).")
    allowed_amount: Optional[float] = Field(None, description="Grand total allowed amount from 'Statement Summary - Allowed Amount' column (e.g., 861.47).")
    provider_discount: Optional[float] = Field(None, description="Grand total provider discount from 'Statement Summary - Provider Discount' column (e.g., -861.47).")
    other_plan_payment: Optional[float] = Field(None, description="Grand total other plan payment from 'Statement Summary - Other Plan Payment' column (e.g., 0.00).")
    other_adjustments: Optional[float] = Field(None, description="Grand total other adjustments from 'Statement Summary - Other Adjustments' column (e.g., 0.00).")
    patient_obligation: Optional[float] = Field(None, description="Grand total patient obligation from 'Statement Summary - Patient Obligation' column (e.g., 470.41).")
    net_payment_amount: Optional[float] = Field(None, description="Grand total net payment from 'Statement Summary - Net Payment Amount' column (e.g., 391.06).")


class DocumentTotal(BaseModel):
    net_payment_amount: Optional[float] = Field(None, description="Net Payment Amount from 'Document Total - Net Payment Amount:' (e.g., 391.06).")
    payment_adjustments: Optional[float] = Field(None, description="Payment Adjustments from 'Document Total - Payment Adjustments:' (e.g., 0.00).")
    total_payment: Optional[float] = Field(None, description="Total Payment from 'Document Total - Total Payment:' (e.g., 391.06).")


class ResponseModel(BaseModel):
    payer_name: Optional[str] = Field(None, description="Payer name (e.g., 'Electronic Payment Clearinghouse' or 'Baylor Scott & White Health Plan').")
    payer_address: Optional[str] = Field(None, description="Payer address (e.g., '1206 West Campus Dr., Temple, TX 76502').")
    payee_name: Optional[str] = Field(None, description="Payee/provider practice name (e.g., 'WILKINSON AND SHAFFER PC').")
    payee_address: Optional[str] = Field(None, description="Payee address (e.g., 'PO BOX 108, SWEETWATER TX 79556').")
    fax_from: Optional[str] = Field(None, description="Fax sender from 'From:' header (e.g., 'Virtual Card Payment  Fax: +14402972748').")
    fax_to: Optional[str] = Field(None, description="Fax recipient from 'To:' header (e.g., 'WILKINSON AND SHAFFER  Fax: +13252358326').")
    received_date: Optional[str] = Field(None, description="Fax received date/time (e.g., '01/17/2026 09:07AM').")
    tran_nbr: Optional[str] = Field(None, description="Transaction number from 'Tran Nbr:' label (e.g., '391321447').")
    card_value: Optional[float] = Field(None, description="Virtual card value from 'Card Value:' label (e.g., 391.06).")
    payment_date: Optional[str] = Field(None, description="Payment date from 'Date:' label (e.g., '01/16/2026').")
    virtual_card_account_number: Optional[str] = Field(None, description="Virtual card account number (e.g., '5328 6410 5928 6844').")
    cvv: Optional[str] = Field(None, description="CVV code from virtual card (e.g., '989').")
    good_thru: Optional[str] = Field(None, description="Card expiry from virtual card (e.g., '04/26').")
    tax_id: Optional[str] = Field(None, description="Tax ID from 'Tax ID:' label (e.g., '201674251').")
    epc_draft_number: Optional[str] = Field(None, description="EPC Draft # from 'EPC Draft #:' label (e.g., '391321447').")
    payment_week: Optional[str] = Field(None, description="Payment week from 'Payment Week:' label (e.g., '2').")
    payment_date_table: Optional[str] = Field(None, description="Payment date from remittance table header 'Payment Date:' label (e.g., '01/16/2026').")
    claims: List[ClaimModel] = Field(default_factory=list, description="All patient claims extracted from the document.")
    statement_summary: Optional[StatementSummary] = Field(None, description="Statement Summary block grand totals.")
    document_total: Optional[DocumentTotal] = Field(None, description="Document Total block with Net Payment Amount, Payment Adjustments, Total Payment.")


class BatchModel(BaseModel):
    claims: List[ClaimModel] = Field(..., description="List of claims found in this batch")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Batch-level metadata")


def map_extracted_data(extracted_claims: List[dict], aggregated_metadata: dict) -> dict:
    nested = aggregated_metadata.get("ocrfax2_remittance_page", {})
    if not isinstance(nested, dict):
        nested = {}
    merged = {**nested, **aggregated_metadata}
    return {
        "payer_name": merged.get("payer_name"),
        "payer_address": merged.get("payer_address"),
        "payee_name": merged.get("payee_name"),
        "payee_address": merged.get("payee_address"),
        "fax_from": merged.get("fax_from"),
        "fax_to": merged.get("fax_to"),
        "received_date": merged.get("received_date"),
        "tran_nbr": merged.get("tran_nbr"),
        "card_value": merged.get("card_value"),
        "payment_date": merged.get("payment_date"),
        "virtual_card_account_number": merged.get("virtual_card_account_number"),
        "cvv": merged.get("cvv"),
        "good_thru": merged.get("good_thru"),
        "tax_id": merged.get("tax_id"),
        "epc_draft_number": merged.get("epc_draft_number"),
        "payment_week": merged.get("payment_week"),
        "payment_date_table": merged.get("payment_date_table"),
        "claims": extracted_claims,
        "statement_summary": merged.get("statement_summary"),
        "document_total": merged.get("document_total"),
    }


SCHEMA_DESCRIPTION = """
This is a QuicRemit/Electronic Payment Clearinghouse Virtual Card Payment fax remittance (ocrfax2).
Document header: payer (Electronic Payment Clearinghouse/Baylor Scott & White Health Plan), payee (WILKINSON AND SHAFFER PC), fax routing, QuicRemit virtual card box (Account Number, CVV, Good Thru), Tran Nbr, Card Value, Date.
Remittance table header: Tax ID, EPC Draft #, Payment Week, Payment Date.
Each claim block: Claim Number, Group ID, Provider, Patient Name, Patient Acct #, Reference Number, Subscriber Name, Subscriber ID, Network.
Service line columns: Service Date | Proc/Rev Code (Modifiers) | Explanation Code(s) | Units | Total Charge | Allowed Amount | Provider Discount | Other Plan Payment | Other Adjustment | Coinsurance | Copay | Deductible | Non-Covered | Net Payment Amount.
Reversal lines (negative units/charges) MUST be included in services — do not skip them.
The 'Claim Total' row MUST be mapped to claim_totals — NEVER into the services list.
Statement Summary at bottom of last page: Total Charge, Allowed Amount, Provider Discount, Other Plan Payment, Other Adjustments, Patient Obligation, Net Payment Amount.
Document Total at bottom right: Net Payment Amount, Payment Adjustments, Total Payment.
Extract ALL 6 claims: 20250922009737 (Michele Domaho), 20250722015531 (ROSEMARY HERNANDEZ), 20250822018479 (Jose Velasquez), 20250803006396 (JOANIE WEHBA), 20250803013009 (HUDSON WEHBA), 20250803006395 (PHYLLIS WILBURN).
"""


def section_builder(text: str) -> List[Dict[str, str]]:
    import re
    sections = []
    pattern = r"Claim\s+Number[:\s]+(\d+)"
    matches = list(re.finditer(pattern, text, re.IGNORECASE))
    if not matches:
        return [{"type": "content", "text": text}]
    for i, match in enumerate(matches):
        start_pos = match.start()
        end_pos = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        sections.append({
            "type": "claim_block",
            "claim_number_hint": match.group(1).strip(),
            "text": text[start_pos:end_pos],
        })
    return sections


def calculate_totals(claims_data: dict) -> dict:
    total_charge = 0.0
    total_net_payment = 0.0
    total_copay = 0.0
    total_coinsurance = 0.0
    claims = (
        claims_data.get("claims")
        or claims_data.get("ocrfax2_remittance_page", {}).get("claims")
        or []
    )
    for claim in claims:
        for svc in claim.get("services", []):
            total_charge += float(svc.get("total_charge") or 0)
            total_net_payment += float(svc.get("net_payment_amount") or 0)
            total_copay += float(svc.get("copay") or 0)
            total_coinsurance += float(svc.get("coinsurance") or 0)
    return {
        "total_charge": round(total_charge, 2),
        "total_net_payment": round(total_net_payment, 2),
        "total_copay": round(total_copay, 2),
        "total_coinsurance": round(total_coinsurance, 2),
    }