# Auto-generated format file for document type: trizetto_testing__1
# Generated by FormatGeneratorAgent on 2026-03-20T10:57:17.530891

from __future__ import annotations
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, field_validator


class ServiceLine(BaseModel):
    """Represents an individual service line within a UnitedHealthcare remittance claim."""

    begin_service_date: Optional[str] = Field(
        None,
        description="Start date of service, 'Begin Service Date' column (e.g., '9/2/2025')."
    )
    end_service_date: Optional[str] = Field(
        None,
        description="End date of service, 'End Service Date' column (e.g., '9/2/2025')."
    )
    rendering_npi: Optional[str] = Field(
        None,
        description="Rendering provider NPI from 'Rendering NPI' column (e.g., '1699763227')."
    )
    paid_units: Optional[int] = Field(
        None,
        description="Number of paid units from 'Paid Units' column (e.g., 1)."
    )
    procedure_code: Optional[str] = Field(
        None,
        description="CPT/HCPCS code from 'Proc/Rev Code, Mods' (e.g., '99213', '92020')."
    )
    modifiers: Optional[str] = Field(
        None,
        description="Procedure modifiers from 'Proc/Rev Code, Mods' (e.g., '25', 'E2'). Space-separated."
    )
    billed_amount: Optional[float] = Field(
        None,
        description="Provider billed amount from 'Billed Amount' column (e.g., 145.00)."
    )
    allowed_amount: Optional[float] = Field(
        None,
        description="Allowed/contractual amount from 'Allowed Amount' column (e.g., 99.89)."
    )
    deduct_amount: Optional[float] = Field(
        None,
        description="Deductible amount from 'Deduct Amount' column (e.g., 0.00)."
    )
    coins_amount: Optional[float] = Field(
        None,
        description="Co-insurance amount from 'CoIns Amount' column (e.g., 0.00)."
    )
    copay_amount: Optional[float] = Field(
        None,
        description="Co-pay amount from 'CoPay Amount' column (e.g., 0.00)."
    )
    late_filing_red: Optional[float] = Field(
        None,
        description="Late filing reduction from 'Late Filing Red.' column (e.g., 0.00)."
    )
    other_adjusts: Optional[float] = Field(
        None,
        description="Total other adjustments from 'Other Adjusts' column (e.g., 47.11)."
    )
    adjust_codes: Optional[str] = Field(
        None,
        description="Adjustment codes from 'Adjust Codes' column (e.g., 'CO-253 CO-45')."
    )
    provider_paid: Optional[float] = Field(
        None,
        description="Net provider payment from 'Provider Paid' column (e.g., 97.89)."
    )
    remark_codes: Optional[str] = Field(
        None,
        description="Remark codes from 'Remark Codes' column (e.g., 'N670'). Null if absent."
    )

    @field_validator("modifiers", "adjust_codes", "remark_codes", mode="before")
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v


class ClaimModel(BaseModel):
    """Represents a full claim for a single patient in UnitedHealthcare remittance."""

    patient_name: Optional[str] = Field(
        None,
        description="Patient full name from 'Patient Name:' label (e.g., 'WAI Y CHU')."
    )
    insured_name: Optional[str] = Field(
        None,
        description="Insured full name from 'Insured Name:' label (e.g., 'WAI Y CHU')."
    )
    claim_id: Optional[str] = Field(
        None,
        description="Unique claim ID from 'Claim ID:' label (e.g., '250909634141')."
    )
    corrected_claim_id: Optional[str] = Field(
        None,
        description="Corrected claim ID if present from 'Corrected Claim ID:' label."
    )
    claim_status: Optional[str] = Field(
        None,
        description="Claim status from 'Claim Status:' label (e.g., 'Processed as Primary')."
    )
    claim_payment_amount: Optional[float] = Field(
        None,
        description="Total claim payment from 'Claim Payment Amount:' label (e.g., 222.79)."
    )
    claim_adj_amt: Optional[float] = Field(
        None,
        description="Claim adjustment amount from 'Claim Adj Amt:' label."
    )
    claim_adj_codes: Optional[str] = Field(
        None,
        description="Claim adjustment codes from 'Claim Adj Codes:' label."
    )
    claim_remark_codes: Optional[str] = Field(
        None,
        description="Claim remark codes from 'Claim Remark Codes:' label (e.g., 'N670')."
    )
    member_identification_number: Optional[str] = Field(
        None,
        description="Member ID from 'Member Identification #:' label (e.g., '120605973')."
    )
    insured_member_identification_number: Optional[str] = Field(
        None,
        description="Insured member ID from 'Insured Member Identification #:' label."
    )
    patient_account_number: Optional[str] = Field(
        None,
        description="Patient account number from 'Patient Account Number:' label (e.g., '111727')."
    )
    rendering_provider: Optional[str] = Field(
        None,
        description="Rendering provider name from 'Rendering Provider:' label (e.g., 'GREGORY L CHIN')."
    )
    rendering_npi: Optional[str] = Field(
        None,
        description="Rendering provider NPI from 'Rendering NPI:' label (e.g., '1699763227')."
    )
    payer_claim_control_number: Optional[str] = Field(
        None,
        description="Payer claim control/ICN from 'Payer Claim Control # / ICN#:' (e.g., '25Q176156100')."
    )
    patient_responsibility: Optional[str] = Field(
        None,
        description="Patient responsibility amount from 'Patient Responsibility:' label."
    )
    patient_responsibility_reason_code: Optional[str] = Field(
        None,
        description="Patient responsibility reason code from label."
    )
    patient_group_number: Optional[str] = Field(
        None,
        description="Patient group number from 'Patient Group#:' label."
    )

    @field_validator(
        "claim_status", "claim_adj_codes", "claim_remark_codes",
        "patient_responsibility_reason_code", mode="before"
    )
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v

    services: List[ServiceLine] = Field(
        default_factory=list,
        description="All service line items within this claim, between column headers and SERVICE LINE TOTALS."
    )
    claim_totals: Optional[ServiceLine] = Field(
        None,
        description="The 'SERVICE LINE TOTALS' row. MANDATORY: map here, NOT in services list."
    )


class ResponseModel(BaseModel):
    """Top-level response model for trizetto_testing__1 (UnitedHealthcare Standard Remittance)."""

    payer_name: Optional[str] = Field(
        None,
        description="Payer name from document header (e.g., 'UnitedHealthcare Community Plan')."
    )
    payer_address: Optional[str] = Field(
        None,
        description="Payer mailing address (e.g., 'PO BOX 5290 KINGSTON, NY 124025290')."
    )
    payee_name: Optional[str] = Field(
        None,
        description="Payee/provider practice name (e.g., 'SEATTLE VISION CLINIC INC')."
    )
    payee_address: Optional[str] = Field(
        None,
        description="Payee mailing address (e.g., '677 S JACKSON ST SEATTLE, WA 98104')."
    )
    eft_number: Optional[str] = Field(
        None,
        description="EFT reference number from 'EFT #:' label (e.g., '25260B1001797377')."
    )
    check_date: Optional[str] = Field(
        None,
        description="Check/EFT issue date from 'Check Date:' label (e.g., '9/19/2025')."
    )
    check_amount: Optional[float] = Field(
        None,
        description="Total check/EFT amount from 'Check Amount:' label (e.g., 1437.79)."
    )
    provider_adj_amt: Optional[float] = Field(
        None,
        description="Provider adjustment amount from 'Provider Adj Amt:' label (e.g., 0.00)."
    )
    provider_number: Optional[str] = Field(
        None,
        description="Provider number from 'Provider #:' label (e.g., '1699763227')."
    )
    provider_tax_id: Optional[str] = Field(
        None,
        description="Provider tax ID from 'Provider Tax ID #:' label (e.g., '911004825')."
    )
    npi_group_provider_number: Optional[str] = Field(
        None,
        description="NPI/Group Provider Number from label (e.g., '1518955202')."
    )
    created_date: Optional[str] = Field(
        None,
        description="Remittance created date from 'Created Date:' label (e.g., '9/18/2025')."
    )
    claims: List[ClaimModel] = Field(
        default_factory=list,
        description="All patient claims extracted from the document."
    )
    check_totals: Optional[Dict[str, Any]] = Field(
        None,
        description="Grand TOTALS row from 'Check Totals' section at end of document."
    )
    adjustment_code_glossary: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="All entries from 'Adjustment Codes Glossary' section."
    )


class BatchModel(BaseModel):
    """Model for validating a single batch of claims."""
    claims: List[ClaimModel] = Field(..., description="List of claims found in this batch")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Batch-level metadata")


def map_extracted_data(extracted_claims: List[dict], aggregated_metadata: dict) -> dict:
    """Maps raw AI extraction output into the final trizetto_testing__1 hierarchy."""
    nested = aggregated_metadata.get("trizetto_testing__1_remittance_page", {})
    if not isinstance(nested, dict):
        nested = {}

    merged = {**nested, **aggregated_metadata}

    return {
        "payer_name": merged.get("payer_name"),
        "payer_address": merged.get("payer_address"),
        "payee_name": merged.get("payee_name"),
        "payee_address": merged.get("payee_address"),
        "eft_number": merged.get("eft_number"),
        "check_date": merged.get("check_date"),
        "check_amount": merged.get("check_amount"),
        "provider_adj_amt": merged.get("provider_adj_amt"),
        "provider_number": merged.get("provider_number"),
        "provider_tax_id": merged.get("provider_tax_id"),
        "npi_group_provider_number": merged.get("npi_group_provider_number"),
        "created_date": merged.get("created_date"),
        "claims": extracted_claims,
        "check_totals": merged.get("check_totals"),
        "adjustment_code_glossary": merged.get("adjustment_code_glossary") or [],
    }


SCHEMA_DESCRIPTION = """
### DOCUMENT TYPE: UnitedHealthcare Standard Remittance (Trizetto/GatewayEDI)

### DOCUMENT STRUCTURE:

1. **CHECK INFORMATION BLOCK** (top of first page):
   - Payer: 'UnitedHealthcare Community Plan', payer address → `payer_name`, `payer_address`
   - Payee: Practice name (e.g., 'SEATTLE VISION CLINIC INC'), payee address → `payee_name`, `payee_address`
   - EFT #, Check Date, Check Amount, Provider Adj Amt → flat metadata fields
   - Provider #, Provider Tax ID #, NPI / Group Provider Number, Created Date → flat metadata fields

2. **CLAIM INFORMATION BLOCKS** (repeating per patient):
   Left side labeled fields: Patient Name, Insured Name, Claim ID (or Corrected Claim ID),
   Claim Status, Claim Payment Amount, Claim Adj Amt, Claim Adj Codes, Claim Remark Codes.
   Right side labeled fields: Member Identification #, Insured Member Identification #,
   Patient Account Number, Rendering Provider, Rendering NPI, Payer Claim Control # / ICN#,
   Patient Responsibility, Patient Responsibility Reason Code, Patient Group#.

3. **SERVICE LINE INFORMATION TABLE** (inside each claim block):
   Columns: Begin Service Date | End Service Date | Rendering NPI | Paid Units |
   Proc/Rev Code, Mods | Billed Amount | Allowed Amount | Deduct Amount |
   CoIns Amount | CoPay Amount | Late Filing Red. | Other Adjusts | Adjust Codes | Provider Paid | Remark Codes

   - procedure_code: base CPT/HCPCS code from 'Proc/Rev Code, Mods' (e.g., '99213', '92134', '68761')
   - modifiers: any modifier suffix after comma (e.g., '25', 'E2', 'E4', '50'). Null if none.
   - other_adjusts: this column shows TWO stacked values (sequestration amount + contractual amount).
     Sum both values for the `other_adjusts` field (e.g., $2.00 + $45.11 = $47.11).
   - adjust_codes: space-separated codes (e.g., 'CO-253 CO-45', 'CO-253 CO-59')
   - SERVICE LINE TOTALS row: MANDATORY → map to `claim_totals`. NEVER add to `services`.

4. **CHECK TOTALS SECTION** (last page):
   Columns: Claim Adjustments | Billed Amount | Allowed Amount | Deduct Amount |
   CoIns Amount | CoPay Amount | Late Filing Red. | Other Adjustments | Total Paid
   Map TOTALS row to `check_totals` dict with keys:
   { claim_adjustments, billed_amount, allowed_amount, deduct_amount, coins_amount,
     copay_amount, late_filing_red, other_adjustments, total_paid }

5. **ADJUSTMENT CODES GLOSSARY** (last page):
   Extract all code definitions into `adjustment_code_glossary`:
   [{ "code": "CO-59", "description": "...", "start_date": "01/01/1995", "last_modified": "09/20/2009" }, ...]

### KEY EXTRACTION RULES:
- **Other Adjusts column**: Contains two stacked dollar amounts per line (CO-253 sequestration + CO-45 contractual).
  Sum them for `other_adjusts`. Example: $2.00 + $45.11 → 47.11.
- **Proc/Rev Code, Mods**: Split on comma → procedure_code + modifiers.
  Example: '99213,25' → procedure_code='99213', modifiers='25'
  Example: '68761,E2' → procedure_code='68761', modifiers='E2'
  Example: '99213' → procedure_code='99213', modifiers=null
- **Corrected Claim**: Some claims show 'Corrected Claim ID:' instead of 'Claim ID:'. Capture in `corrected_claim_id`.
- **Insured Name Corrected**: Insured name may show 'DINHVY V LUONG Corrected' — strip 'Corrected' suffix.
- **Every claim MUST have claim_totals** from the SERVICE LINE TOTALS row.
- **All 7 claims** must be extracted: WAI Y CHU, LI P GUO, YU Q LI, DINH V LUONG, NGA ONG, SIU WONG, XIMING ZHAO.
"""


def section_builder(text: str) -> List[Dict[str, str]]:
    """Identify trizetto_testing__1 claim block boundaries using regex on raw text."""
    import re
    sections = []

    pattern = r"Patient\s+Name:\s*([A-Z ,.\-']+)"
    matches = list(re.finditer(pattern, text, re.IGNORECASE))

    if not matches:
        return [{"type": "content", "text": text}]

    for i, match in enumerate(matches):
        start_pos = match.start()
        end_pos = matches[i + 1].start() if i + 1 < len(matches) else len(text)

        sections.append({
            "type": "claim_block",
            "patient_hint": match.group(1).strip(),
            "text": text[start_pos:end_pos],
        })

    return sections


def calculate_totals(claims_data: dict) -> dict:
    """Calculate format-specific totals for the final trizetto_testing__1 response."""
    total_billed = 0.0
    total_paid = 0.0
    total_other_adjusts = 0.0
    total_allowed = 0.0

    claims = (
        claims_data.get("claims")
        or claims_data.get("trizetto_testing__1_remittance_page", {}).get("claims")
        or []
    )

    for claim in claims:
        services = claim.get("services", [])
        for svc in services:
            total_billed += float(svc.get("billed_amount") or 0)
            total_paid += float(svc.get("provider_paid") or 0)
            total_other_adjusts += float(svc.get("other_adjusts") or 0)
            total_allowed += float(svc.get("allowed_amount") or 0)

    return {
        "total_billed": round(total_billed, 2),
        "total_paid": round(total_paid, 2),
        "total_other_adjusts": round(total_other_adjusts, 2),
        "total_allowed": round(total_allowed, 2),
    }