# Auto-generated format file for document type: xxxxxx1
# Generated by FormatGeneratorAgent on 2026-03-06T13:59:37.450729

# Auto-generated format file for document type: xxxxxx1
# Generated by FormatGeneratorAgent

from __future__ import annotations
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field, field_validator


class ServiceLineItem(BaseModel):
    """
    Represents an individual service line within an xxxxxx1 (AETNA Standard Remittance) claim.
    Maps to each row in the 'Service Line Information' table between column headers and 'SERVICE LINE TOTALS'.
    """

    begin_service_date: Optional[str] = Field(
        None,
        description="Start date of the service from the 'Begin Service Date' column in MM/DD/YYYY format (e.g., '2/12/2026', '2/10/2026', '2/11/2026')."
    )
    end_service_date: Optional[str] = Field(
        None,
        description="End date of the service from the 'End Service Date' column in MM/DD/YYYY format (e.g., '2/12/2026'). Usually the same as begin_service_date."
    )
    rendering_npi: Optional[str] = Field(
        None,
        description="NPI of the rendering provider for this service line from the 'Rendering NPI' column (e.g., '1922147503')."
    )
    paid_units: Optional[int] = Field(
        None,
        description="Number of paid units from the 'Paid Units' column (e.g., 1, 0)."
    )
    procedure_code: Optional[str] = Field(
        None,
        description="The CPT/HCPCS procedure code from the 'Proc/Rev Code, Mods' column (e.g., '99213', '92133', '92083', '92015', '92014', '92133', '76514')."
    )
    modifiers: Optional[str] = Field(
        None,
        description="Any procedure code modifiers from the 'Proc/Rev Code, Mods' column (e.g., 'GT', '25'). Separate multiple with a space. Null if no modifier."
    )
    billed_amount: Optional[float] = Field(
        None,
        description="Amount billed by the provider from the 'Billed Amount' column (e.g., 120.00, 70.00, 115.00, 45.00, 160.00)."
    )
    allowed_amount: Optional[float] = Field(
        None,
        description="Allowed/contractual amount from the 'Allowed Amount' column per fee schedule (e.g., 87.57, 39.27, 75.07, 22.36, 142.42)."
    )
    deduct_amount: Optional[float] = Field(
        None,
        description="Deductible amount applied from the 'Deduct Amount' column (e.g., 0.00)."
    )
    coins_amount: Optional[float] = Field(
        None,
        description="Co-insurance amount applied from the 'CoIns Amount' column (e.g., 0.00, 2.24, 14.24)."
    )
    copay_amount: Optional[float] = Field(
        None,
        description="Co-pay amount from the 'CoPay Amount' column representing patient responsibility (e.g., 45.00, 0.00, 30.00)."
    )
    late_filing_red: Optional[float] = Field(
        None,
        description="Late filing reduction amount from the 'Late Filing Red.' column (e.g., 0.00)."
    )
    other_adjusts: Optional[float] = Field(
        None,
        description="Other adjustment amount from the 'Other Adjusts' column (e.g., 32.43, 30.73, 39.93, 22.64, 17.58, 26.63, 40.00)."
    )
    adjust_codes: Optional[str] = Field(
        None,
        description="All adjustment reason codes from the 'Adjust Codes' column (e.g., 'CO-45', 'CO-59', 'CO-119'). Separate multiple with a space."
    )
    provider_paid: Optional[float] = Field(
        None,
        description="Net amount paid to the provider from the 'Provider Paid' column (e.g., 42.57, 39.27, 75.07, 20.12, 128.18, 13.37, 22.36, 142.42, 0.00)."
    )
    remark_codes: Optional[str] = Field(
        None,
        description="Remark codes from the 'Remark Codes' column (e.g., 'N640'). Separate multiple with a space. Null if absent."
    )

    @field_validator("modifiers", "adjust_codes", "remark_codes", mode="before")
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v


class ClaimModel(BaseModel):
    """
    Represents a full claim for a single patient within an xxxxxx1 (AETNA Standard Remittance) document.
    Each claim block is delimited by a 'Claim Information' section header.
    """

    patient_name: Optional[str] = Field(
        None,
        description="Full name of the patient from 'Patient Name:' label (e.g., 'KAJAL PATEL', 'PAMELA PETERSEN-CRAIR', 'KERRY ROSA')."
    )
    member_identification_number: Optional[str] = Field(
        None,
        description="Patient's member identification number from 'Member Identification #:' label (e.g., 'W296853284', 'W287393855')."
    )
    insured_name: Optional[str] = Field(
        None,
        description="Full name of the insured/subscriber from 'Insured Name:' label (e.g., 'KAJAL PATEL', 'MICHAEL CRAIR', 'FREDERICK ROSA')."
    )
    insured_member_identification_number: Optional[str] = Field(
        None,
        description="Insured member identification number from 'Insured Member Identification #:' label (e.g., 'W296853284', 'W224964116', 'W287393855')."
    )
    claim_id: Optional[str] = Field(
        None,
        description="Unique claim identifier from 'Claim ID:' label (e.g., '260213519183', '260212432390', '260212453258')."
    )
    patient_account_number: Optional[str] = Field(
        None,
        description="Provider-assigned patient account number from 'Patient Account Number:' label (e.g., '150477817', '150267506', '150406416')."
    )
    claim_status: Optional[str] = Field(
        None,
        description="Processing status from 'Claim Status:' label (e.g., 'Processed as Primary')."
    )
    rendering_provider: Optional[str] = Field(
        None,
        description="Name of the rendering provider from 'Rendering Provider:' label (e.g., 'CHRISTIAN B SWENBY', 'BETSY F SWENBY')."
    )
    rendering_npi: Optional[str] = Field(
        None,
        description="NPI of the rendering provider from 'Rendering NPI:' label (e.g., '1922147503')."
    )
    payer_claim_control_number: Optional[str] = Field(
        None,
        description="Payer Claim Control # / ICN# from 'Payer Claim Control # / ICN#:' label (e.g., 'EFY2T0DMR0000', 'EDFDTZK830000', 'E8PDR0JRH0000')."
    )
    claim_payment_amount: Optional[float] = Field(
        None,
        description="Total amount paid by the payer for this claim from 'Claim Payment Amount:' label (e.g., 156.91, 148.30, 178.15)."
    )
    claim_adjustment_amount: Optional[float] = Field(
        None,
        description="Claim-level adjustment amount from 'Claim Adj Amt:' label, if any."
    )
    claim_adjustment_codes: Optional[str] = Field(
        None,
        description="Claim-level adjustment codes from 'Claim Adj Codes:' label. Separate multiple with a space."
    )
    claim_remark_codes: Optional[str] = Field(
        None,
        description="Claim-level remark codes from 'Claim Remark Codes:' label. Separate multiple with a space."
    )
    patient_responsibility: Optional[float] = Field(
        None,
        description="Total patient responsibility amount from 'Patient Responsibility:' label (e.g., 45.00, 16.48, 30.00)."
    )
    patient_responsibility_reason_code: Optional[str] = Field(
        None,
        description="Reason code for patient responsibility from 'Patient Responsibility Reason Code:' label (e.g., 'PR-3', 'PR-2, PR-2')."
    )
    patient_group_number: Optional[str] = Field(
        None,
        description="Patient group/plan number from 'Patient Group#:' label (e.g., '0187676-014-00003-CA', '0877076-013-00007-HB', '0237574-010-00031-A')."
    )

    @field_validator(
        "claim_status", "claim_adjustment_codes", "claim_remark_codes",
        "patient_responsibility_reason_code", mode="before"
    )
    @classmethod
    def convert_list_to_string(cls, v: Any) -> Any:
        if isinstance(v, list):
            return " ".join([str(i) for i in v if i is not None])
        return v

    services: List[ServiceLineItem] = Field(
        default_factory=list,
        description="All individual service line items within this claim. Each data row between the column headers and 'SERVICE LINE TOTALS'."
    )
    claim_totals: Optional[ServiceLineItem] = Field(
        None,
        description=(
            "The 'SERVICE LINE TOTALS' summary row for this claim. "
            "MANDATORY: Map this row to claim_totals — do NOT include it in the services list. "
            "Contains summed Billed Amount, Allowed Amount, Deduct Amount, CoIns Amount, "
            "CoPay Amount, Late Filing Red., Other Adjusts, and Provider Paid."
        )
    )


class ResponseModel(BaseModel):
    """
    Top-level response model for the xxxxxx1 (AETNA Standard Remittance) document.
    Matches the flat output of map_extracted_data directly.
    """

    payer_name: Optional[str] = Field(
        None,
        description="Name of the insurance payer (e.g., 'AETNA')."
    )
    payer_address: Optional[str] = Field(
        None,
        description="Payer mailing address as printed on the document (e.g., '151 FARMINGTON AVENUE, HARTFORD, CT 06156')."
    )
    payee_name: Optional[str] = Field(
        None,
        description="Name of the practice/payee receiving the payment (e.g., 'VISUALEYES LLC')."
    )
    payee_address: Optional[str] = Field(
        None,
        description="Payee mailing address as printed on the document (e.g., '705 BOSTON POST RD STE 10A, GUILFORD, CT 064372733')."
    )
    provider_number: Optional[str] = Field(
        None,
        description="Provider number from 'Provider #:' label (e.g., '679335060')."
    )
    provider_tax_id: Optional[str] = Field(
        None,
        description="Provider Tax ID from 'Provider Tax ID #:' label (e.g., '830365527')."
    )
    eft_number: Optional[str] = Field(
        None,
        description="Electronic Funds Transfer reference number from 'EFT #:' label (e.g., '826051000213853')."
    )
    npi_group_provider_number: Optional[str] = Field(
        None,
        description="NPI or Group Provider Number from 'NPI / Group Provider Number:' label (e.g., '1922147503')."
    )
    check_date: Optional[str] = Field(
        None,
        description="Date the check/EFT was issued from 'Check Date:' label (e.g., '2/25/2026')."
    )
    created_date: Optional[str] = Field(
        None,
        description="Date the remittance was created from 'Created Date:' label (e.g., '2/21/2026')."
    )
    check_amount: Optional[float] = Field(
        None,
        description="Total check/EFT payment amount from 'Check Amount:' label (e.g., 483.36)."
    )
    provider_adjustment_amount: Optional[float] = Field(
        None,
        description="Provider-level adjustment amount from 'Provider Adj Amt:' label (e.g., 0.00)."
    )
    claims: List[ClaimModel] = Field(
        default_factory=list,
        description="A comprehensive list of every patient claim extracted from the document."
    )
    check_totals: Optional[Dict[str, Any]] = Field(
        None,
        description="The grand 'TOTALS' summary row from the 'Check Totals' section at the bottom of the remittance."
    )
    adjustment_code_glossary: Optional[List[Dict[str, Any]]] = Field(
        default_factory=list,
        description="All adjustment and remark code definitions from the 'Adjustment Codes Glossary' section."
    )


class BatchModel(BaseModel):
    """Model for validating a single batch of claims."""
    claims: List[ClaimModel] = Field(..., description="List of claims found in this batch")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Batch-level metadata")


def map_extracted_data(extracted_claims: List[dict], aggregated_metadata: dict) -> dict:
    """
    Maps raw AI extraction output into the final xxxxxx1 (AETNA Standard Remittance) hierarchy.
    The AI returns metadata as flat keys inside the BatchModel 'metadata' field.
    """
    # The AI may nest data under a document-type key OR return it flat
    nested = aggregated_metadata.get("xxxxxx1_remittance_page", {})
    if not isinstance(nested, dict):
        nested = {}

    # Merge: flat keys take precedence over any nested wrapper
    merged = {**nested, **aggregated_metadata}

    return {
        "payer_name": merged.get("payer_name"),
        "payer_address": merged.get("payer_address"),
        "payee_name": merged.get("payee_name"),
        "payee_address": merged.get("payee_address"),
        "provider_number": merged.get("provider_number"),
        "provider_tax_id": merged.get("provider_tax_id"),
        "eft_number": merged.get("eft_number"),
        "npi_group_provider_number": merged.get("npi_group_provider_number"),
        "check_date": merged.get("check_date"),
        "created_date": merged.get("created_date"),
        "check_amount": merged.get("check_amount"),
        "provider_adjustment_amount": merged.get("provider_adjustment_amount"),
        "claims": extracted_claims,
        "check_totals": merged.get("check_totals"),
        "adjustment_code_glossary": merged.get("adjustment_code_glossary") or [],
    }


SCHEMA_DESCRIPTION = """
### HIERARCHICAL ANALYSIS METHODOLOGY:
**CRITICAL**: Study each page's visual hierarchy in detail before extraction:
1. **Scan the Document Header** ('Check Information' box): Locate payer name/address, payee name/address,
   Provider #, Provider Tax ID #, EFT #, NPI / Group Provider Number, Check Date, Created Date,
   Check Amount, Provider Adj Amt.
2. **Identify Claim Blocks**: Each 'Claim Information' box introduces a new patient claim.
3. **Analyze Claim Structure**:
   - **Claim Information box** (top): Contains all labeled header fields (Patient Name, Member ID, etc.)
   - **Service Line Information table**: Column headers row followed by service line rows.
   - **SERVICE LINE TOTALS row**: Bottom row of the service table — MANDATORY: map to `claim_totals`,
     NEVER into `services`.
4. **Capture Check Totals**: The 'TOTALS:' row in the 'Check Totals' box → `check_totals`.
5. **Capture Glossary**: All entries under 'Adjustment Codes Glossary' → `adjustment_code_glossary`.

### AETNA STANDARD REMITTANCE DOCUMENT STRUCTURE:

1. **DOCUMENT-LEVEL HEADER** ('Check Information' box, top of first page):
   - Left side: Payer name (AETNA), payer address, payee name (VISUALEYES LLC), payee address.
   - Left side continued: EFT #, Check Date, Check Amount, Provider Adj Amt.
   - Right side: Provider #, Provider Tax ID #, NPI / Group Provider Number, Created Date.
   Map to: payer_name, payer_address, payee_name, payee_address, provider_number, provider_tax_id,
   eft_number, npi_group_provider_number, check_date, created_date, check_amount, provider_adjustment_amount.

2. **PATIENT CLAIM BLOCKS** (each 'Claim Information' box):
   Left side labeled fields:
   - Patient Name (e.g., 'KAJAL PATEL')
   - Insured Name (e.g., 'KAJAL PATEL')
   - Claim ID (e.g., '260213519183')
   - Claim Status (e.g., 'Processed as Primary')
   - Claim Payment Amount (e.g., '$156.91')
   - Claim Adj Amt (may be blank)
   - Claim Adj Codes (may be blank)
   - Claim Remark Codes (may be blank)
   Right side labeled fields:
   - Member Identification # (e.g., 'W296853284')
   - Insured Member Identification # (e.g., 'W296853284')
   - Patient Account Number (e.g., '150477817')
   - Rendering Provider (e.g., 'CHRISTIAN B SWENBY')
   - Rendering NPI (e.g., '1922147503')
   - Payer Claim Control # / ICN# (e.g., 'EFY2T0DMR0000')
   - Patient Responsibility (e.g., '$45.00')
   - Patient Responsibility Reason Code (e.g., 'PR-3')
   - Patient Group# (e.g., '0187676-014-00003-CA')

3. **SERVICE LINE INFORMATION TABLE** (inside each claim block):
   Column headers (left to right):
   Begin Service Date | End Service Date | Rendering NPI | Paid Units |
   Proc/Rev Code, Mods | Billed Amount | Allowed Amount | Deduct Amount |
   CoIns Amount | CoPay Amount | Late Filing Red. | Other Adjusts | Adjust Codes | Provider Paid | Remark Codes

   **SERVICE LINE ROWS** (extract ALL rows before 'SERVICE LINE TOTALS'):
   - begin_service_date: e.g., '2/12/2026'
   - end_service_date: e.g., '2/12/2026'
   - rendering_npi: e.g., '1922147503'
   - paid_units: integer e.g., 1, 0
   - procedure_code: CPT/HCPCS code from 'Proc/Rev Code, Mods' (e.g., '99213', '92133', '92083', '92015', '92014', '76514')
   - modifiers: modifier appended in same column (e.g., null if no modifier shown)
   - billed_amount: float (e.g., 120.00, 70.00, 115.00, 45.00, 160.00, 40.00)
   - allowed_amount: float (e.g., 87.57, 39.27, 75.07, 22.36, 142.42, 0.00)
   - deduct_amount: float (e.g., 0.00)
   - coins_amount: float (e.g., 0.00, 2.24, 14.24)
   - copay_amount: float (e.g., 45.00, 0.00, 30.00)
   - late_filing_red: float (e.g., 0.00)
   - other_adjusts: float — sum of all other adjustment dollar amounts on the line (e.g., 32.43, 30.73, 39.93, 22.64, 17.58, 26.63, 40.00)
   - adjust_codes: space-separated all adjustment codes on the line (e.g., 'CO-45', 'CO-59', 'CO-119')
   - provider_paid: float — net amount paid to provider (e.g., 42.57, 39.27, 75.07, 20.12, 128.18, 0.00)
   - remark_codes: space-separated remark codes (e.g., 'N640') or null if absent

   **SERVICE LINE TOTALS row**: Labeled 'SERVICE LINE TOTALS:' — MANDATORY: map to `claim_totals`.
   NEVER add this row to the `services` list.

4. **CHECK TOTALS SECTION** (second page, 'Check Totals' box):
   Columns: Claim Adjustments | Billed Amount | Allowed Amount | Deduct Amount |
   CoIns Amount | CoPay Amount | Late Filing Red. | Other Adjustments | Total Paid
   Map the 'TOTALS:' row to `check_totals` dict:
   {
     "claim_adjustments": 0.00,
     "billed_amount": 825.00,
     "allowed_amount": 574.84,
     "deduct_amount": 0.00,
     "coins_amount": 16.48,
     "copay_amount": 75.00,
     "late_filing_red": 0.00,
     "other_adjustments": 250.16,
     "total_paid": 483.36
   }

5. **ADJUSTMENT CODES GLOSSARY** (second page, below Check Totals):
   Groups and codes appear in a hierarchical structure:
   - Category heading (bold, e.g., 'Billed Service Not Covered by Health Plan')
   - Code entries under each category (e.g., 'CO-119 : Benefit maximum...', 'CO-59 : Processed based...')
   - Group-level entries (e.g., 'CO : Contractual Obligations...')
   - Additional code entries (e.g., 'CO-45 : Charge exceeds fee schedule...')
   - Group-level entries (e.g., 'PR : Patient Responsibility')
   - Code entries (e.g., 'PR-2 : Coinsurance Amount...', 'PR-3 : Co-payment Amount...')

   Extract each entry into `adjustment_code_glossary`:
   [
     { "category": "Billed Service Not Covered by Health Plan", "code": "CO-119",
       "group": "CO", "description": "Benefit maximum for this time period or occurrence has been reached.",
       "start_date": "01/01/1995", "last_modified_date": "02/29/2004", "notes": null },
     { "category": "Billed Service Not Covered by Health Plan", "code": "CO-59",
       "group": "CO", "description": "Processed based on multiple or concurrent procedure rules...",
       "start_date": "01/01/1995", "last_modified_date": "09/20/2009", "notes": "Refer to the 835 Healthcare Policy Identification Segment..." },
     { "category": "Billed Service Not Covered by Health Plan", "code": "N640",
       "group": "N", "description": "Exceeds number/frequency approved/allowed within time period.",
       "start_date": "07/15/2013", "last_modified_date": null, "notes": null },
     { "category": "Contractual Obligations", "code": "CO",
       "group": "CO", "description": "Contractual Obligations: Use this code when a joint payer/payee contractual agreement or a regulatory requirement resulted in an adjustment.",
       "start_date": null, "last_modified_date": null, "notes": null },
     { "category": "Contractual Obligations", "code": "CO-45",
       "group": "CO", "description": "Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement...",
       "start_date": "01/01/1995", "last_modified_date": "11/01/2015", "notes": null },
     { "category": "Patient Responsibility", "code": "PR",
       "group": "PR", "description": "Patient Responsibility",
       "start_date": null, "last_modified_date": null, "notes": null },
     { "category": "Patient Responsibility", "code": "PR-2",
       "group": "PR", "description": "Coinsurance Amount",
       "start_date": "01/01/1995", "last_modified_date": null, "notes": null },
     { "category": "Patient Responsibility", "code": "PR-3",
       "group": "PR", "description": "Co-payment Amount",
       "start_date": "01/01/1995", "last_modified_date": null, "notes": null }
   ]

### FIELD EXTRACTION NOTES:

- **EFT #**: From 'EFT #:' label on the left side of Check Information box (e.g., '826051000213853').
- **Check Amount**: From 'Check Amount:' label (e.g., '$483.36' → 483.36).
- **Provider Adj Amt**: From 'Provider Adj Amt:' label (e.g., '$0.00' → 0.00).
- **Claim Payment Amount**: Strip dollar sign and parse to float (e.g., '$156.91' → 156.91).
- **Patient Responsibility**: Strip dollar sign (e.g., '$45.00' → 45.00).
- **Patient Responsibility Reason Code**: May contain multiple codes (e.g., 'PR-2, PR-2').
  Capture as-is or space-separated.
- **Patient Group#**: Alphanumeric string (e.g., '0187676-014-00003-CA'). Always treat as string.
- **Payer Claim Control # / ICN#**: Alphanumeric string (e.g., 'EFY2T0DMR0000'). Always string.
- **Rendering NPI on service lines**: May be repeated for each line (e.g., '1922147503').
- **Paid Units = 0**: Some service lines may show 0 paid units (e.g., procedure 76514 with 0 units).
  Still extract the line into `services`.
- **Adjust Codes**: Single code per line typically (e.g., 'CO-45', 'CO-59', 'CO-119').
- **Remark Codes on service lines**: Only present on specific lines (e.g., 'N640' on the 76514 line).
  Leave null for lines without remark codes.
- **CoIns Amount on SERVICE LINE TOTALS**: Sum of all CoIns amounts across service lines.
- **CoPay Amount on SERVICE LINE TOTALS**: Sum of all CoPay amounts across service lines.

### ZERO DATA LOSS RULES:
- Every claim MUST have `claim_totals`. Retrieve from the 'SERVICE LINE TOTALS:' row.
- ALL service lines per claim must be extracted — do not skip any line.
- `check_totals` is MANDATORY when the 'Check Totals' section exists with a 'TOTALS:' row.
- `adjustment_code_glossary` must be fully extracted — do not return an empty list if entries exist.
- Service lines with 0 paid units or $0.00 provider paid must still be included in `services`.
- `remark_codes` on service lines: null if no remark code column value is present for that line.
- All three claim blocks on page 1 must be extracted completely — KAJAL PATEL, PAMELA PETERSEN-CRAIR, KERRY ROSA.
- `patient_responsibility_reason_code` may contain multiple codes separated by comma (e.g., 'PR-2, PR-2').
"""


def section_builder(text: str) -> List[Dict[str, str]]:
    """
    Identify xxxxxx1 (AETNA Standard Remittance) claim block boundaries using regex on raw text.
    Each claim block is introduced by a 'Claim Information' header with 'Patient Name:'.
    """
    import re
    sections = []

    pattern = r"Patient\s+Name:\s*([A-Z ,.\-']+)"
    matches = list(re.finditer(pattern, text, re.IGNORECASE))

    if not matches:
        return [{"type": "content", "text": text}]

    for i, match in enumerate(matches):
        start_pos = match.start()
        end_pos = matches[i + 1].start() if i + 1 < len(matches) else len(text)

        sections.append({
            "type": "claim_block",
            "patient_hint": match.group(1).strip(),
            "text": text[start_pos:end_pos],
        })

    return sections


def calculate_totals(claims_data: dict) -> dict:
    """Calculate format-specific totals for the final xxxxxx1 (AETNA Standard Remittance) response."""
    total_billed = 0.0
    total_paid = 0.0
    total_patient_responsibility = 0.0
    total_other_adjusts = 0.0

    # claims is at top level (flat dict from map_extracted_data)
    claims = (
        claims_data.get("claims")
        or claims_data.get("xxxxxx1_remittance_page", {}).get("claims")
        or []
    )

    for claim in claims:
        services = claim.get("services", [])
        for svc in services:
            total_billed += float(svc.get("billed_amount") or 0)
            total_paid += float(svc.get("provider_paid") or 0)
            total_patient_responsibility += float(svc.get("copay_amount") or 0)
            total_other_adjusts += float(svc.get("other_adjusts") or 0)

    return {
        "total_billed": round(total_billed, 2),
        "total_paid": round(total_paid, 2),
        "total_patient_responsibility": round(total_patient_responsibility, 2),
        "total_other_adjusts": round(total_other_adjusts, 2),
    }